apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: fdb-profile-analyzer
  name: {{ .JobName }}
  namespace: {{ .Namespace }}
spec:
  template:
    metadata:
      labels:
        app: fdb-profile-analyzer
    spec:
      initContainers:
        - args:
            - --copy-library
            - "6.2"
            - --output-dir
            - /var/output-files/6.2.30
            - --init-mode
          image: foundationdb/foundationdb-kubernetes-sidecar:6.2.30-1
          name: foundationdb-kubernetes-init-6-2
          volumeMounts:
            - mountPath: /var/output-files
              name: fdb-binaries
        - args:
            - --copy-library
            - "6.3"
            - --output-dir
            - /var/output-files/6.3.24
            - --init-mode
          image: foundationdb/foundationdb-kubernetes-sidecar:6.3.24-1
          name: foundationdb-kubernetes-init-6-3
          volumeMounts:
            - mountPath: /var/output-files
              name: fdb-binaries
        - args:
            - --copy-library
            - "7.1"
            - --output-dir
            - /var/output-files/7.1.19
            - --init-mode
          image: foundationdb/foundationdb-kubernetes-sidecar:7.1.19-1
          name: foundationdb-kubernetes-init-7-1
          volumeMounts:
            - mountPath: /var/output-files
              name: fdb-binaries
      containers:
        - command:
            - /bin/bash
          args:
            - -c
            - python3 ./transaction_profiling_analyzer.py {{ .CommandArgs }}
          env:
            - name: FDB_CLUSTER_FILE
              value: /var/dynamic-conf/fdb.cluster
            - name: FDB_NETWORK_OPTION_TRACE_ENABLE
              value: /var/log/fdb-profile-analyzer
            - name: FDB_NETWORK_OPTION_TRACE_FORMAT
              value: json
          image: fdb-profile-analyzer:latest
          imagePullPolicy: Always
          name: profile-analyzer
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - mountPath: /var/dynamic-conf
              name: config-map
              readOnly: true
            - mountPath: /var/log/fdb-profile-analyzer
              name: fdb-profile-analyzer-logs
            - mountPath: /usr/bin/fdb
              name: fdb-binaries
      restartPolicy: Never
      securityContext:
        fsGroup: 4059
        runAsGroup: 4059
        runAsUser: 4059
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: cluster-file
                path: fdb.cluster
            name: {{ .ClusterName }}-config
          name: config-map
        - emptyDir: {}
          name: fdb-profile-analyzer-logs
        - emptyDir: {}
          name: fdb-binaries
  ttlSecondsAfterFinished: 7200
