apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdb-kubernetes-operator-controller-manager
  labels:
    {{- include "chart.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.operator.name }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 40590
        runAsGroup: 40590
        fsGroup: 40590
      volumes:
      - name: tmp
        emptyDir: {}
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        {{- if not .Values.operator.globalMode.enabled }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- end }}
        image: {{ .Values.operator.image }}:{{ .Values.operator.tag }}
        imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics   
        volumeMounts:
        - name: tmp
          mountPath: /tmp       
        resources:
          {{- toYaml .Values.resources | nindent 12 }}     
        securityContext:
          readOnlyRootFilesystem: true  
          allowPrivilegeEscalation: false   
          privileged: false          
      serviceAccountName: fdb-kubernetes-operator-controller-manager
      terminationGracePeriodSeconds: 10
