//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 FoundationDB project authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"github.com/FoundationDB/fdb-kubernetes-operator/pkg/fdb"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomaticReplacementOptions) DeepCopyInto(out *AutomaticReplacementOptions) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FailureDetectionTimeSeconds != nil {
		in, out := &in.FailureDetectionTimeSeconds, &out.FailureDetectionTimeSeconds
		*out = new(int)
		**out = **in
	}
	if in.MaxConcurrentReplacements != nil {
		in, out := &in.MaxConcurrentReplacements, &out.MaxConcurrentReplacements
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomaticReplacementOptions.
func (in *AutomaticReplacementOptions) DeepCopy() *AutomaticReplacementOptions {
	if in == nil {
		return nil
	}
	out := new(AutomaticReplacementOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupGenerationStatus) DeepCopyInto(out *BackupGenerationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupGenerationStatus.
func (in *BackupGenerationStatus) DeepCopy() *BackupGenerationStatus {
	if in == nil {
		return nil
	}
	out := new(BackupGenerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStoreConfiguration) DeepCopyInto(out *BlobStoreConfiguration) {
	*out = *in
	if in.URLParameters != nil {
		in, out := &in.URLParameters, &out.URLParameters
		*out = make([]URLParameter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStoreConfiguration.
func (in *BlobStoreConfiguration) DeepCopy() *BlobStoreConfiguration {
	if in == nil {
		return nil
	}
	out := new(BlobStoreConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuggifyConfig) DeepCopyInto(out *BuggifyConfig) {
	*out = *in
	if in.NoSchedule != nil {
		in, out := &in.NoSchedule, &out.NoSchedule
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CrashLoop != nil {
		in, out := &in.CrashLoop, &out.CrashLoop
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuggifyConfig.
func (in *BuggifyConfig) DeepCopy() *BuggifyConfig {
	if in == nil {
		return nil
	}
	out := new(BuggifyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGenerationStatus) DeepCopyInto(out *ClusterGenerationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGenerationStatus.
func (in *ClusterGenerationStatus) DeepCopy() *ClusterGenerationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGenerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealth) DeepCopyInto(out *ClusterHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealth.
func (in *ClusterHealth) DeepCopy() *ClusterHealth {
	if in == nil {
		return nil
	}
	out := new(ClusterHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionString) DeepCopyInto(out *ConnectionString) {
	*out = *in
	if in.Coordinators != nil {
		in, out := &in.Coordinators, &out.Coordinators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionString.
func (in *ConnectionString) DeepCopy() *ConnectionString {
	if in == nil {
		return nil
	}
	out := new(ConnectionString)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerOverrides) DeepCopyInto(out *ContainerOverrides) {
	*out = *in
	if in.EnableLivenessProbe != nil {
		in, out := &in.EnableLivenessProbe, &out.EnableLivenessProbe
		*out = new(bool)
		**out = **in
	}
	if in.EnableReadinessProbe != nil {
		in, out := &in.EnableReadinessProbe, &out.EnableReadinessProbe
		*out = new(bool)
		**out = **in
	}
	if in.ImageConfigs != nil {
		in, out := &in.ImageConfigs, &out.ImageConfigs
		*out = make([]ImageConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerOverrides.
func (in *ContainerOverrides) DeepCopy() *ContainerOverrides {
	if in == nil {
		return nil
	}
	out := new(ContainerOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorSelectionSetting) DeepCopyInto(out *CoordinatorSelectionSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorSelectionSetting.
func (in *CoordinatorSelectionSetting) DeepCopy() *CoordinatorSelectionSetting {
	if in == nil {
		return nil
	}
	out := new(CoordinatorSelectionSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackup) DeepCopyInto(out *FoundationDBBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackup.
func (in *FoundationDBBackup) DeepCopy() *FoundationDBBackup {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupList) DeepCopyInto(out *FoundationDBBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundationDBBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupList.
func (in *FoundationDBBackupList) DeepCopy() *FoundationDBBackupList {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupSpec) DeepCopyInto(out *FoundationDBBackupSpec) {
	*out = *in
	if in.AgentCount != nil {
		in, out := &in.AgentCount, &out.AgentCount
		*out = new(int)
		**out = **in
	}
	if in.SnapshotPeriodSeconds != nil {
		in, out := &in.SnapshotPeriodSeconds, &out.SnapshotPeriodSeconds
		*out = new(int)
		**out = **in
	}
	if in.BackupDeploymentMetadata != nil {
		in, out := &in.BackupDeploymentMetadata, &out.BackupDeploymentMetadata
		*out = new(v1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplateSpec != nil {
		in, out := &in.PodTemplateSpec, &out.PodTemplateSpec
		*out = new(corev1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomParameters != nil {
		in, out := &in.CustomParameters, &out.CustomParameters
		*out = make(fdb.FoundationDBCustomParameters, len(*in))
		copy(*out, *in)
	}
	if in.AllowTagOverride != nil {
		in, out := &in.AllowTagOverride, &out.AllowTagOverride
		*out = new(bool)
		**out = **in
	}
	if in.BlobStoreConfiguration != nil {
		in, out := &in.BlobStoreConfiguration, &out.BlobStoreConfiguration
		*out = new(BlobStoreConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupSpec.
func (in *FoundationDBBackupSpec) DeepCopy() *FoundationDBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupStatus) DeepCopyInto(out *FoundationDBBackupStatus) {
	*out = *in
	if in.BackupDetails != nil {
		in, out := &in.BackupDetails, &out.BackupDetails
		*out = new(FoundationDBBackupStatusBackupDetails)
		**out = **in
	}
	out.Generations = in.Generations
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupStatus.
func (in *FoundationDBBackupStatus) DeepCopy() *FoundationDBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupStatusBackupDetails) DeepCopyInto(out *FoundationDBBackupStatusBackupDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupStatusBackupDetails.
func (in *FoundationDBBackupStatusBackupDetails) DeepCopy() *FoundationDBBackupStatusBackupDetails {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupStatusBackupDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBCluster) DeepCopyInto(out *FoundationDBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBCluster.
func (in *FoundationDBCluster) DeepCopy() *FoundationDBCluster {
	if in == nil {
		return nil
	}
	out := new(FoundationDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterAutomationOptions) DeepCopyInto(out *FoundationDBClusterAutomationOptions) {
	*out = *in
	if in.ConfigureDatabase != nil {
		in, out := &in.ConfigureDatabase, &out.ConfigureDatabase
		*out = new(bool)
		**out = **in
	}
	if in.KillProcesses != nil {
		in, out := &in.KillProcesses, &out.KillProcesses
		*out = new(bool)
		**out = **in
	}
	in.Replacements.DeepCopyInto(&out.Replacements)
	if in.UseNonBlockingExcludes != nil {
		in, out := &in.UseNonBlockingExcludes, &out.UseNonBlockingExcludes
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreTerminatingPodsSeconds != nil {
		in, out := &in.IgnoreTerminatingPodsSeconds, &out.IgnoreTerminatingPodsSeconds
		*out = new(int)
		**out = **in
	}
	if in.MaxConcurrentReplacements != nil {
		in, out := &in.MaxConcurrentReplacements, &out.MaxConcurrentReplacements
		*out = new(int)
		**out = **in
	}
	if in.WaitBetweenRemovalsSeconds != nil {
		in, out := &in.WaitBetweenRemovalsSeconds, &out.WaitBetweenRemovalsSeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterAutomationOptions.
func (in *FoundationDBClusterAutomationOptions) DeepCopy() *FoundationDBClusterAutomationOptions {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterAutomationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterFaultDomain) DeepCopyInto(out *FoundationDBClusterFaultDomain) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterFaultDomain.
func (in *FoundationDBClusterFaultDomain) DeepCopy() *FoundationDBClusterFaultDomain {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterFaultDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterList) DeepCopyInto(out *FoundationDBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundationDBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterList.
func (in *FoundationDBClusterList) DeepCopy() *FoundationDBClusterList {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterSpec) DeepCopyInto(out *FoundationDBClusterSpec) {
	*out = *in
	in.DatabaseConfiguration.DeepCopyInto(&out.DatabaseConfiguration)
	if in.Processes != nil {
		in, out := &in.Processes, &out.Processes
		*out = make(map[fdb.ProcessClass]ProcessSettings, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.ProcessCounts = in.ProcessCounts
	in.PartialConnectionString.DeepCopyInto(&out.PartialConnectionString)
	out.FaultDomain = in.FaultDomain
	if in.ProcessGroupsToRemove != nil {
		in, out := &in.ProcessGroupsToRemove, &out.ProcessGroupsToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcessGroupsToRemoveWithoutExclusion != nil {
		in, out := &in.ProcessGroupsToRemoveWithoutExclusion, &out.ProcessGroupsToRemoveWithoutExclusion
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(corev1.ConfigMap)
		(*in).DeepCopyInto(*out)
	}
	in.MainContainer.DeepCopyInto(&out.MainContainer)
	in.SidecarContainer.DeepCopyInto(&out.SidecarContainer)
	if in.TrustedCAs != nil {
		in, out := &in.TrustedCAs, &out.TrustedCAs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SidecarVariables != nil {
		in, out := &in.SidecarVariables, &out.SidecarVariables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.AutomationOptions.DeepCopyInto(&out.AutomationOptions)
	in.LockOptions.DeepCopyInto(&out.LockOptions)
	in.Routing.DeepCopyInto(&out.Routing)
	in.Buggify.DeepCopyInto(&out.Buggify)
	if in.ReplaceInstancesWhenResourcesChange != nil {
		in, out := &in.ReplaceInstancesWhenResourcesChange, &out.ReplaceInstancesWhenResourcesChange
		*out = new(bool)
		**out = **in
	}
	if in.CoordinatorSelection != nil {
		in, out := &in.CoordinatorSelection, &out.CoordinatorSelection
		*out = make([]CoordinatorSelectionSetting, len(*in))
		copy(*out, *in)
	}
	in.LabelConfig.DeepCopyInto(&out.LabelConfig)
	if in.UseExplicitListenAddress != nil {
		in, out := &in.UseExplicitListenAddress, &out.UseExplicitListenAddress
		*out = new(bool)
		**out = **in
	}
	if in.UseUnifiedImage != nil {
		in, out := &in.UseUnifiedImage, &out.UseUnifiedImage
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterSpec.
func (in *FoundationDBClusterSpec) DeepCopy() *FoundationDBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterStatus) DeepCopyInto(out *FoundationDBClusterStatus) {
	*out = *in
	in.DatabaseConfiguration.DeepCopyInto(&out.DatabaseConfiguration)
	out.Generations = in.Generations
	out.Health = in.Health
	out.RequiredAddresses = in.RequiredAddresses
	if in.StorageServersPerDisk != nil {
		in, out := &in.StorageServersPerDisk, &out.StorageServersPerDisk
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ImageTypes != nil {
		in, out := &in.ImageTypes, &out.ImageTypes
		*out = make([]ImageType, len(*in))
		copy(*out, *in)
	}
	if in.ProcessGroups != nil {
		in, out := &in.ProcessGroups, &out.ProcessGroups
		*out = make([]*ProcessGroupStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProcessGroupStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.Locks.DeepCopyInto(&out.Locks)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterStatus.
func (in *FoundationDBClusterStatus) DeepCopy() *FoundationDBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBKeyRange) DeepCopyInto(out *FoundationDBKeyRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBKeyRange.
func (in *FoundationDBKeyRange) DeepCopy() *FoundationDBKeyRange {
	if in == nil {
		return nil
	}
	out := new(FoundationDBKeyRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBLiveBackupStatus) DeepCopyInto(out *FoundationDBLiveBackupStatus) {
	*out = *in
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBLiveBackupStatus.
func (in *FoundationDBLiveBackupStatus) DeepCopy() *FoundationDBLiveBackupStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBLiveBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBLiveBackupStatusState) DeepCopyInto(out *FoundationDBLiveBackupStatusState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBLiveBackupStatusState.
func (in *FoundationDBLiveBackupStatusState) DeepCopy() *FoundationDBLiveBackupStatusState {
	if in == nil {
		return nil
	}
	out := new(FoundationDBLiveBackupStatusState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestore) DeepCopyInto(out *FoundationDBRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestore.
func (in *FoundationDBRestore) DeepCopy() *FoundationDBRestore {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestoreList) DeepCopyInto(out *FoundationDBRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundationDBRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestoreList.
func (in *FoundationDBRestoreList) DeepCopy() *FoundationDBRestoreList {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestoreSpec) DeepCopyInto(out *FoundationDBRestoreSpec) {
	*out = *in
	if in.KeyRanges != nil {
		in, out := &in.KeyRanges, &out.KeyRanges
		*out = make([]FoundationDBKeyRange, len(*in))
		copy(*out, *in)
	}
	if in.BlobStoreConfiguration != nil {
		in, out := &in.BlobStoreConfiguration, &out.BlobStoreConfiguration
		*out = new(BlobStoreConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomParameters != nil {
		in, out := &in.CustomParameters, &out.CustomParameters
		*out = make(fdb.FoundationDBCustomParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestoreSpec.
func (in *FoundationDBRestoreSpec) DeepCopy() *FoundationDBRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestoreStatus) DeepCopyInto(out *FoundationDBRestoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestoreStatus.
func (in *FoundationDBRestoreStatus) DeepCopy() *FoundationDBRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelConfig) DeepCopyInto(out *LabelConfig) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceLabels != nil {
		in, out := &in.ResourceLabels, &out.ResourceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ProcessGroupIDLabels != nil {
		in, out := &in.ProcessGroupIDLabels, &out.ProcessGroupIDLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcessClassLabels != nil {
		in, out := &in.ProcessClassLabels, &out.ProcessClassLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FilterOnOwnerReferences != nil {
		in, out := &in.FilterOnOwnerReferences, &out.FilterOnOwnerReferences
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelConfig.
func (in *LabelConfig) DeepCopy() *LabelConfig {
	if in == nil {
		return nil
	}
	out := new(LabelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LockDenyListEntry) DeepCopyInto(out *LockDenyListEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LockDenyListEntry.
func (in *LockDenyListEntry) DeepCopy() *LockDenyListEntry {
	if in == nil {
		return nil
	}
	out := new(LockDenyListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LockOptions) DeepCopyInto(out *LockOptions) {
	*out = *in
	if in.DisableLocks != nil {
		in, out := &in.DisableLocks, &out.DisableLocks
		*out = new(bool)
		**out = **in
	}
	if in.LockDurationMinutes != nil {
		in, out := &in.LockDurationMinutes, &out.LockDurationMinutes
		*out = new(int)
		**out = **in
	}
	if in.DenyList != nil {
		in, out := &in.DenyList, &out.DenyList
		*out = make([]LockDenyListEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LockOptions.
func (in *LockOptions) DeepCopy() *LockOptions {
	if in == nil {
		return nil
	}
	out := new(LockOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LockSystemStatus) DeepCopyInto(out *LockSystemStatus) {
	*out = *in
	if in.DenyList != nil {
		in, out := &in.DenyList, &out.DenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LockSystemStatus.
func (in *LockSystemStatus) DeepCopy() *LockSystemStatus {
	if in == nil {
		return nil
	}
	out := new(LockSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessGroupCondition) DeepCopyInto(out *ProcessGroupCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessGroupCondition.
func (in *ProcessGroupCondition) DeepCopy() *ProcessGroupCondition {
	if in == nil {
		return nil
	}
	out := new(ProcessGroupCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessGroupStatus) DeepCopyInto(out *ProcessGroupStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemovalTimestamp != nil {
		in, out := &in.RemovalTimestamp, &out.RemovalTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ExclusionTimestamp != nil {
		in, out := &in.ExclusionTimestamp, &out.ExclusionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ProcessGroupConditions != nil {
		in, out := &in.ProcessGroupConditions, &out.ProcessGroupConditions
		*out = make([]*ProcessGroupCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProcessGroupCondition)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessGroupStatus.
func (in *ProcessGroupStatus) DeepCopy() *ProcessGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessSettings) DeepCopyInto(out *ProcessSettings) {
	*out = *in
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(corev1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(corev1.PersistentVolumeClaim)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomParameters != nil {
		in, out := &in.CustomParameters, &out.CustomParameters
		*out = make(fdb.FoundationDBCustomParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessSettings.
func (in *ProcessSettings) DeepCopy() *ProcessSettings {
	if in == nil {
		return nil
	}
	out := new(ProcessSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredAddressSet) DeepCopyInto(out *RequiredAddressSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredAddressSet.
func (in *RequiredAddressSet) DeepCopy() *RequiredAddressSet {
	if in == nil {
		return nil
	}
	out := new(RequiredAddressSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingConfig) DeepCopyInto(out *RoutingConfig) {
	*out = *in
	if in.HeadlessService != nil {
		in, out := &in.HeadlessService, &out.HeadlessService
		*out = new(bool)
		**out = **in
	}
	if in.PublicIPSource != nil {
		in, out := &in.PublicIPSource, &out.PublicIPSource
		*out = new(PublicIPSource)
		**out = **in
	}
	if in.PodIPFamily != nil {
		in, out := &in.PodIPFamily, &out.PodIPFamily
		*out = new(int)
		**out = **in
	}
	if in.UseDNSInClusterFile != nil {
		in, out := &in.UseDNSInClusterFile, &out.UseDNSInClusterFile
		*out = new(bool)
		**out = **in
	}
	if in.DNSDomain != nil {
		in, out := &in.DNSDomain, &out.DNSDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingConfig.
func (in *RoutingConfig) DeepCopy() *RoutingConfig {
	if in == nil {
		return nil
	}
	out := new(RoutingConfig)
	in.DeepCopyInto(out)
	return out
}
