//go:build !ignore_autogenerated

/*
Copyright 2020 FoundationDB project authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	netx "net"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomaticReplacementOptions) DeepCopyInto(out *AutomaticReplacementOptions) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FaultDomainBasedReplacements != nil {
		in, out := &in.FaultDomainBasedReplacements, &out.FaultDomainBasedReplacements
		*out = new(bool)
		**out = **in
	}
	if in.FailureDetectionTimeSeconds != nil {
		in, out := &in.FailureDetectionTimeSeconds, &out.FailureDetectionTimeSeconds
		*out = new(int)
		**out = **in
	}
	if in.TaintReplacementTimeSeconds != nil {
		in, out := &in.TaintReplacementTimeSeconds, &out.TaintReplacementTimeSeconds
		*out = new(int)
		**out = **in
	}
	if in.MaxConcurrentReplacements != nil {
		in, out := &in.MaxConcurrentReplacements, &out.MaxConcurrentReplacements
		*out = new(int)
		**out = **in
	}
	if in.TaintReplacementOptions != nil {
		in, out := &in.TaintReplacementOptions, &out.TaintReplacementOptions
		*out = make([]TaintReplacementOption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxFaultDomainsWithTaintedProcessGroups != nil {
		in, out := &in.MaxFaultDomainsWithTaintedProcessGroups, &out.MaxFaultDomainsWithTaintedProcessGroups
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomaticReplacementOptions.
func (in *AutomaticReplacementOptions) DeepCopy() *AutomaticReplacementOptions {
	if in == nil {
		return nil
	}
	out := new(AutomaticReplacementOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupGenerationStatus) DeepCopyInto(out *BackupGenerationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupGenerationStatus.
func (in *BackupGenerationStatus) DeepCopy() *BackupGenerationStatus {
	if in == nil {
		return nil
	}
	out := new(BackupGenerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStoreConfiguration) DeepCopyInto(out *BlobStoreConfiguration) {
	*out = *in
	if in.URLParameters != nil {
		in, out := &in.URLParameters, &out.URLParameters
		*out = make([]URLParameter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStoreConfiguration.
func (in *BlobStoreConfiguration) DeepCopy() *BlobStoreConfiguration {
	if in == nil {
		return nil
	}
	out := new(BlobStoreConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuggifyConfig) DeepCopyInto(out *BuggifyConfig) {
	*out = *in
	if in.NoSchedule != nil {
		in, out := &in.NoSchedule, &out.NoSchedule
		*out = make([]ProcessGroupID, len(*in))
		copy(*out, *in)
	}
	if in.CrashLoop != nil {
		in, out := &in.CrashLoop, &out.CrashLoop
		*out = make([]ProcessGroupID, len(*in))
		copy(*out, *in)
	}
	if in.CrashLoopContainers != nil {
		in, out := &in.CrashLoopContainers, &out.CrashLoopContainers
		*out = make([]CrashLoopContainerObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IgnoreDuringRestart != nil {
		in, out := &in.IgnoreDuringRestart, &out.IgnoreDuringRestart
		*out = make([]ProcessGroupID, len(*in))
		copy(*out, *in)
	}
	if in.BlockRemoval != nil {
		in, out := &in.BlockRemoval, &out.BlockRemoval
		*out = make([]ProcessGroupID, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuggifyConfig.
func (in *BuggifyConfig) DeepCopy() *BuggifyConfig {
	if in == nil {
		return nil
	}
	out := new(BuggifyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGenerationStatus) DeepCopyInto(out *ClusterGenerationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGenerationStatus.
func (in *ClusterGenerationStatus) DeepCopy() *ClusterGenerationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGenerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealth) DeepCopyInto(out *ClusterHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealth.
func (in *ClusterHealth) DeepCopy() *ClusterHealth {
	if in == nil {
		return nil
	}
	out := new(ClusterHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionString) DeepCopyInto(out *ConnectionString) {
	*out = *in
	if in.Coordinators != nil {
		in, out := &in.Coordinators, &out.Coordinators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionString.
func (in *ConnectionString) DeepCopy() *ConnectionString {
	if in == nil {
		return nil
	}
	out := new(ConnectionString)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerOverrides) DeepCopyInto(out *ContainerOverrides) {
	*out = *in
	if in.EnableLivenessProbe != nil {
		in, out := &in.EnableLivenessProbe, &out.EnableLivenessProbe
		*out = new(bool)
		**out = **in
	}
	if in.EnableReadinessProbe != nil {
		in, out := &in.EnableReadinessProbe, &out.EnableReadinessProbe
		*out = new(bool)
		**out = **in
	}
	if in.ImageConfigs != nil {
		in, out := &in.ImageConfigs, &out.ImageConfigs
		*out = make([]ImageConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerOverrides.
func (in *ContainerOverrides) DeepCopy() *ContainerOverrides {
	if in == nil {
		return nil
	}
	out := new(ContainerOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorSelectionSetting) DeepCopyInto(out *CoordinatorSelectionSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorSelectionSetting.
func (in *CoordinatorSelectionSetting) DeepCopy() *CoordinatorSelectionSetting {
	if in == nil {
		return nil
	}
	out := new(CoordinatorSelectionSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrashLoopContainerObject) DeepCopyInto(out *CrashLoopContainerObject) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ProcessGroupID, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrashLoopContainerObject.
func (in *CrashLoopContainerObject) DeepCopy() *CrashLoopContainerObject {
	if in == nil {
		return nil
	}
	out := new(CrashLoopContainerObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCenter) DeepCopyInto(out *DataCenter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCenter.
func (in *DataCenter) DeepCopy() *DataCenter {
	if in == nil {
		return nil
	}
	out := new(DataCenter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfiguration) DeepCopyInto(out *DatabaseConfiguration) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]Region, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludedServers != nil {
		in, out := &in.ExcludedServers, &out.ExcludedServers
		*out = make([]ExcludedServers, len(*in))
		copy(*out, *in)
	}
	out.RoleCounts = in.RoleCounts
	out.VersionFlags = in.VersionFlags
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfiguration.
func (in *DatabaseConfiguration) DeepCopy() *DatabaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExcludedServers) DeepCopyInto(out *ExcludedServers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludedServers.
func (in *ExcludedServers) DeepCopy() *ExcludedServers {
	if in == nil {
		return nil
	}
	out := new(ExcludedServers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultTolerance) DeepCopyInto(out *FaultTolerance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultTolerance.
func (in *FaultTolerance) DeepCopy() *FaultTolerance {
	if in == nil {
		return nil
	}
	out := new(FaultTolerance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackup) DeepCopyInto(out *FoundationDBBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackup.
func (in *FoundationDBBackup) DeepCopy() *FoundationDBBackup {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupList) DeepCopyInto(out *FoundationDBBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundationDBBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupList.
func (in *FoundationDBBackupList) DeepCopy() *FoundationDBBackupList {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupSpec) DeepCopyInto(out *FoundationDBBackupSpec) {
	*out = *in
	if in.AgentCount != nil {
		in, out := &in.AgentCount, &out.AgentCount
		*out = new(int)
		**out = **in
	}
	if in.SnapshotPeriodSeconds != nil {
		in, out := &in.SnapshotPeriodSeconds, &out.SnapshotPeriodSeconds
		*out = new(int)
		**out = **in
	}
	if in.BackupDeploymentMetadata != nil {
		in, out := &in.BackupDeploymentMetadata, &out.BackupDeploymentMetadata
		*out = new(v1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplateSpec != nil {
		in, out := &in.PodTemplateSpec, &out.PodTemplateSpec
		*out = new(corev1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomParameters != nil {
		in, out := &in.CustomParameters, &out.CustomParameters
		*out = make(FoundationDBCustomParameters, len(*in))
		copy(*out, *in)
	}
	if in.AllowTagOverride != nil {
		in, out := &in.AllowTagOverride, &out.AllowTagOverride
		*out = new(bool)
		**out = **in
	}
	if in.BlobStoreConfiguration != nil {
		in, out := &in.BlobStoreConfiguration, &out.BlobStoreConfiguration
		*out = new(BlobStoreConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.MainContainer.DeepCopyInto(&out.MainContainer)
	in.SidecarContainer.DeepCopyInto(&out.SidecarContainer)
	if in.ImageType != nil {
		in, out := &in.ImageType, &out.ImageType
		*out = new(ImageType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupSpec.
func (in *FoundationDBBackupSpec) DeepCopy() *FoundationDBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupStatus) DeepCopyInto(out *FoundationDBBackupStatus) {
	*out = *in
	if in.BackupDetails != nil {
		in, out := &in.BackupDetails, &out.BackupDetails
		*out = new(FoundationDBBackupStatusBackupDetails)
		**out = **in
	}
	out.Generations = in.Generations
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupStatus.
func (in *FoundationDBBackupStatus) DeepCopy() *FoundationDBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBackupStatusBackupDetails) DeepCopyInto(out *FoundationDBBackupStatusBackupDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBackupStatusBackupDetails.
func (in *FoundationDBBackupStatusBackupDetails) DeepCopy() *FoundationDBBackupStatusBackupDetails {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBackupStatusBackupDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBBounceImpact) DeepCopyInto(out *FoundationDBBounceImpact) {
	*out = *in
	if in.CanCleanBounce != nil {
		in, out := &in.CanCleanBounce, &out.CanCleanBounce
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBBounceImpact.
func (in *FoundationDBBounceImpact) DeepCopy() *FoundationDBBounceImpact {
	if in == nil {
		return nil
	}
	out := new(FoundationDBBounceImpact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBCluster) DeepCopyInto(out *FoundationDBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBCluster.
func (in *FoundationDBCluster) DeepCopy() *FoundationDBCluster {
	if in == nil {
		return nil
	}
	out := new(FoundationDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterAutomationOptions) DeepCopyInto(out *FoundationDBClusterAutomationOptions) {
	*out = *in
	if in.ConfigureDatabase != nil {
		in, out := &in.ConfigureDatabase, &out.ConfigureDatabase
		*out = new(bool)
		**out = **in
	}
	if in.KillProcesses != nil {
		in, out := &in.KillProcesses, &out.KillProcesses
		*out = new(bool)
		**out = **in
	}
	if in.CacheDatabaseStatusForReconciliation != nil {
		in, out := &in.CacheDatabaseStatusForReconciliation, &out.CacheDatabaseStatusForReconciliation
		*out = new(bool)
		**out = **in
	}
	in.Replacements.DeepCopyInto(&out.Replacements)
	if in.UseNonBlockingExcludes != nil {
		in, out := &in.UseNonBlockingExcludes, &out.UseNonBlockingExcludes
		*out = new(bool)
		**out = **in
	}
	if in.UseLocalitiesForExclusion != nil {
		in, out := &in.UseLocalitiesForExclusion, &out.UseLocalitiesForExclusion
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreTerminatingPodsSeconds != nil {
		in, out := &in.IgnoreTerminatingPodsSeconds, &out.IgnoreTerminatingPodsSeconds
		*out = new(int)
		**out = **in
	}
	if in.IgnoreMissingProcessesSeconds != nil {
		in, out := &in.IgnoreMissingProcessesSeconds, &out.IgnoreMissingProcessesSeconds
		*out = new(int)
		**out = **in
	}
	if in.FailedPodDurationSeconds != nil {
		in, out := &in.FailedPodDurationSeconds, &out.FailedPodDurationSeconds
		*out = new(int)
		**out = **in
	}
	if in.MaxConcurrentReplacements != nil {
		in, out := &in.MaxConcurrentReplacements, &out.MaxConcurrentReplacements
		*out = new(int)
		**out = **in
	}
	if in.WaitBetweenRemovalsSeconds != nil {
		in, out := &in.WaitBetweenRemovalsSeconds, &out.WaitBetweenRemovalsSeconds
		*out = new(int)
		**out = **in
	}
	if in.UseManagementAPI != nil {
		in, out := &in.UseManagementAPI, &out.UseManagementAPI
		*out = new(bool)
		**out = **in
	}
	in.MaintenanceModeOptions.DeepCopyInto(&out.MaintenanceModeOptions)
	if in.IgnoreLogGroupsForUpgrade != nil {
		in, out := &in.IgnoreLogGroupsForUpgrade, &out.IgnoreLogGroupsForUpgrade
		*out = make([]LogGroup, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterAutomationOptions.
func (in *FoundationDBClusterAutomationOptions) DeepCopy() *FoundationDBClusterAutomationOptions {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterAutomationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterFaultDomain) DeepCopyInto(out *FoundationDBClusterFaultDomain) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterFaultDomain.
func (in *FoundationDBClusterFaultDomain) DeepCopy() *FoundationDBClusterFaultDomain {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterFaultDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterList) DeepCopyInto(out *FoundationDBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundationDBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterList.
func (in *FoundationDBClusterList) DeepCopy() *FoundationDBClusterList {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterSpec) DeepCopyInto(out *FoundationDBClusterSpec) {
	*out = *in
	in.DatabaseConfiguration.DeepCopyInto(&out.DatabaseConfiguration)
	if in.Processes != nil {
		in, out := &in.Processes, &out.Processes
		*out = make(map[ProcessClass]ProcessSettings, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.ProcessCounts = in.ProcessCounts
	in.PartialConnectionString.DeepCopyInto(&out.PartialConnectionString)
	out.FaultDomain = in.FaultDomain
	if in.ProcessGroupsToRemove != nil {
		in, out := &in.ProcessGroupsToRemove, &out.ProcessGroupsToRemove
		*out = make([]ProcessGroupID, len(*in))
		copy(*out, *in)
	}
	if in.ProcessGroupsToRemoveWithoutExclusion != nil {
		in, out := &in.ProcessGroupsToRemoveWithoutExclusion, &out.ProcessGroupsToRemoveWithoutExclusion
		*out = make([]ProcessGroupID, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(corev1.ConfigMap)
		(*in).DeepCopyInto(*out)
	}
	in.MainContainer.DeepCopyInto(&out.MainContainer)
	in.SidecarContainer.DeepCopyInto(&out.SidecarContainer)
	if in.TrustedCAs != nil {
		in, out := &in.TrustedCAs, &out.TrustedCAs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SidecarVariables != nil {
		in, out := &in.SidecarVariables, &out.SidecarVariables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.AutomationOptions.DeepCopyInto(&out.AutomationOptions)
	in.LockOptions.DeepCopyInto(&out.LockOptions)
	in.Routing.DeepCopyInto(&out.Routing)
	in.Buggify.DeepCopyInto(&out.Buggify)
	if in.ReplaceInstancesWhenResourcesChange != nil {
		in, out := &in.ReplaceInstancesWhenResourcesChange, &out.ReplaceInstancesWhenResourcesChange
		*out = new(bool)
		**out = **in
	}
	if in.CoordinatorSelection != nil {
		in, out := &in.CoordinatorSelection, &out.CoordinatorSelection
		*out = make([]CoordinatorSelectionSetting, len(*in))
		copy(*out, *in)
	}
	in.LabelConfig.DeepCopyInto(&out.LabelConfig)
	if in.UseExplicitListenAddress != nil {
		in, out := &in.UseExplicitListenAddress, &out.UseExplicitListenAddress
		*out = new(bool)
		**out = **in
	}
	if in.ImageType != nil {
		in, out := &in.ImageType, &out.ImageType
		*out = new(ImageType)
		**out = **in
	}
	if in.EnableNodeWatch != nil {
		in, out := &in.EnableNodeWatch, &out.EnableNodeWatch
		*out = new(bool)
		**out = **in
	}
	if in.MaxZonesWithUnavailablePods != nil {
		in, out := &in.MaxZonesWithUnavailablePods, &out.MaxZonesWithUnavailablePods
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterSpec.
func (in *FoundationDBClusterSpec) DeepCopy() *FoundationDBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBClusterStatus) DeepCopyInto(out *FoundationDBClusterStatus) {
	*out = *in
	in.DatabaseConfiguration.DeepCopyInto(&out.DatabaseConfiguration)
	out.Generations = in.Generations
	out.Health = in.Health
	out.RequiredAddresses = in.RequiredAddresses
	if in.StorageServersPerDisk != nil {
		in, out := &in.StorageServersPerDisk, &out.StorageServersPerDisk
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.LogServersPerDisk != nil {
		in, out := &in.LogServersPerDisk, &out.LogServersPerDisk
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ImageTypes != nil {
		in, out := &in.ImageTypes, &out.ImageTypes
		*out = make([]ImageType, len(*in))
		copy(*out, *in)
	}
	if in.ProcessGroups != nil {
		in, out := &in.ProcessGroups, &out.ProcessGroups
		*out = make([]*ProcessGroupStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProcessGroupStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.Locks.DeepCopyInto(&out.Locks)
	in.MaintenanceModeInfo.DeepCopyInto(&out.MaintenanceModeInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBClusterStatus.
func (in *FoundationDBClusterStatus) DeepCopy() *FoundationDBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FoundationDBCustomParameters) DeepCopyInto(out *FoundationDBCustomParameters) {
	{
		in := &in
		*out = make(FoundationDBCustomParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBCustomParameters.
func (in FoundationDBCustomParameters) DeepCopy() FoundationDBCustomParameters {
	if in == nil {
		return nil
	}
	out := new(FoundationDBCustomParameters)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBKeyRange) DeepCopyInto(out *FoundationDBKeyRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBKeyRange.
func (in *FoundationDBKeyRange) DeepCopy() *FoundationDBKeyRange {
	if in == nil {
		return nil
	}
	out := new(FoundationDBKeyRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBLiveBackupStatus) DeepCopyInto(out *FoundationDBLiveBackupStatus) {
	*out = *in
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBLiveBackupStatus.
func (in *FoundationDBLiveBackupStatus) DeepCopy() *FoundationDBLiveBackupStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBLiveBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBLiveBackupStatusState) DeepCopyInto(out *FoundationDBLiveBackupStatusState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBLiveBackupStatusState.
func (in *FoundationDBLiveBackupStatusState) DeepCopy() *FoundationDBLiveBackupStatusState {
	if in == nil {
		return nil
	}
	out := new(FoundationDBLiveBackupStatusState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestore) DeepCopyInto(out *FoundationDBRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestore.
func (in *FoundationDBRestore) DeepCopy() *FoundationDBRestore {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestoreList) DeepCopyInto(out *FoundationDBRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundationDBRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestoreList.
func (in *FoundationDBRestoreList) DeepCopy() *FoundationDBRestoreList {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundationDBRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestoreSpec) DeepCopyInto(out *FoundationDBRestoreSpec) {
	*out = *in
	if in.KeyRanges != nil {
		in, out := &in.KeyRanges, &out.KeyRanges
		*out = make([]FoundationDBKeyRange, len(*in))
		copy(*out, *in)
	}
	if in.BlobStoreConfiguration != nil {
		in, out := &in.BlobStoreConfiguration, &out.BlobStoreConfiguration
		*out = new(BlobStoreConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomParameters != nil {
		in, out := &in.CustomParameters, &out.CustomParameters
		*out = make(FoundationDBCustomParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestoreSpec.
func (in *FoundationDBRestoreSpec) DeepCopy() *FoundationDBRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBRestoreStatus) DeepCopyInto(out *FoundationDBRestoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBRestoreStatus.
func (in *FoundationDBRestoreStatus) DeepCopy() *FoundationDBRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatus) DeepCopyInto(out *FoundationDBStatus) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatus.
func (in *FoundationDBStatus) DeepCopy() *FoundationDBStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusBackupInfo) DeepCopyInto(out *FoundationDBStatusBackupInfo) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]FoundationDBStatusBackupTag, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusBackupInfo.
func (in *FoundationDBStatusBackupInfo) DeepCopy() *FoundationDBStatusBackupInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusBackupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusBackupTag) DeepCopyInto(out *FoundationDBStatusBackupTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusBackupTag.
func (in *FoundationDBStatusBackupTag) DeepCopy() *FoundationDBStatusBackupTag {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusBackupTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusClientDBStatus) DeepCopyInto(out *FoundationDBStatusClientDBStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusClientDBStatus.
func (in *FoundationDBStatusClientDBStatus) DeepCopy() *FoundationDBStatusClientDBStatus {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusClientDBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusClusterClientInfo) DeepCopyInto(out *FoundationDBStatusClusterClientInfo) {
	*out = *in
	if in.SupportedVersions != nil {
		in, out := &in.SupportedVersions, &out.SupportedVersions
		*out = make([]FoundationDBStatusSupportedVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusClusterClientInfo.
func (in *FoundationDBStatusClusterClientInfo) DeepCopy() *FoundationDBStatusClusterClientInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusClusterClientInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusClusterInfo) DeepCopyInto(out *FoundationDBStatusClusterInfo) {
	*out = *in
	in.DatabaseConfiguration.DeepCopyInto(&out.DatabaseConfiguration)
	if in.Processes != nil {
		in, out := &in.Processes, &out.Processes
		*out = make(map[ProcessGroupID]FoundationDBStatusProcessInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Data.DeepCopyInto(&out.Data)
	in.Clients.DeepCopyInto(&out.Clients)
	in.Layers.DeepCopyInto(&out.Layers)
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = make([]FoundationDBStatusLogInfo, len(*in))
		copy(*out, *in)
	}
	out.Qos = in.Qos
	out.FaultTolerance = in.FaultTolerance
	if in.IncompatibleConnections != nil {
		in, out := &in.IncompatibleConnections, &out.IncompatibleConnections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.RecoveryState = in.RecoveryState
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]FoundationDBStatusMessage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.BounceImpact.DeepCopyInto(&out.BounceImpact)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusClusterInfo.
func (in *FoundationDBStatusClusterInfo) DeepCopy() *FoundationDBStatusClusterInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusConnectedClient) DeepCopyInto(out *FoundationDBStatusConnectedClient) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusConnectedClient.
func (in *FoundationDBStatusConnectedClient) DeepCopy() *FoundationDBStatusConnectedClient {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusConnectedClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusCoordinator) DeepCopyInto(out *FoundationDBStatusCoordinator) {
	*out = *in
	in.Address.DeepCopyInto(&out.Address)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusCoordinator.
func (in *FoundationDBStatusCoordinator) DeepCopy() *FoundationDBStatusCoordinator {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusCoordinator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusCoordinatorInfo) DeepCopyInto(out *FoundationDBStatusCoordinatorInfo) {
	*out = *in
	if in.Coordinators != nil {
		in, out := &in.Coordinators, &out.Coordinators
		*out = make([]FoundationDBStatusCoordinator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusCoordinatorInfo.
func (in *FoundationDBStatusCoordinatorInfo) DeepCopy() *FoundationDBStatusCoordinatorInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusCoordinatorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusDataState) DeepCopyInto(out *FoundationDBStatusDataState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusDataState.
func (in *FoundationDBStatusDataState) DeepCopy() *FoundationDBStatusDataState {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusDataState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusDataStatistics) DeepCopyInto(out *FoundationDBStatusDataStatistics) {
	*out = *in
	out.MovingData = in.MovingData
	out.State = in.State
	if in.TeamTrackers != nil {
		in, out := &in.TeamTrackers, &out.TeamTrackers
		*out = make([]FoundationDBStatusTeamTracker, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusDataStatistics.
func (in *FoundationDBStatusDataStatistics) DeepCopy() *FoundationDBStatusDataStatistics {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusDataStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusLagInfo) DeepCopyInto(out *FoundationDBStatusLagInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusLagInfo.
func (in *FoundationDBStatusLagInfo) DeepCopy() *FoundationDBStatusLagInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusLagInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusLayerInfo) DeepCopyInto(out *FoundationDBStatusLayerInfo) {
	*out = *in
	in.Backup.DeepCopyInto(&out.Backup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusLayerInfo.
func (in *FoundationDBStatusLayerInfo) DeepCopy() *FoundationDBStatusLayerInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusLayerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusLocalClientInfo) DeepCopyInto(out *FoundationDBStatusLocalClientInfo) {
	*out = *in
	in.Coordinators.DeepCopyInto(&out.Coordinators)
	out.DatabaseStatus = in.DatabaseStatus
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]FoundationDBStatusMessage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusLocalClientInfo.
func (in *FoundationDBStatusLocalClientInfo) DeepCopy() *FoundationDBStatusLocalClientInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusLocalClientInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusLogInfo) DeepCopyInto(out *FoundationDBStatusLogInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusLogInfo.
func (in *FoundationDBStatusLogInfo) DeepCopy() *FoundationDBStatusLogInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusLogInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusMessage) DeepCopyInto(out *FoundationDBStatusMessage) {
	*out = *in
	if in.UnreachableProcesses != nil {
		in, out := &in.UnreachableProcesses, &out.UnreachableProcesses
		*out = make([]FoundationDBUnreachableProcess, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusMessage.
func (in *FoundationDBStatusMessage) DeepCopy() *FoundationDBStatusMessage {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusMovingData) DeepCopyInto(out *FoundationDBStatusMovingData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusMovingData.
func (in *FoundationDBStatusMovingData) DeepCopy() *FoundationDBStatusMovingData {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusMovingData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusProcessInfo) DeepCopyInto(out *FoundationDBStatusProcessInfo) {
	*out = *in
	in.Address.DeepCopyInto(&out.Address)
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]FoundationDBStatusProcessRoleInfo, len(*in))
		copy(*out, *in)
	}
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]FoundationDBStatusProcessMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusProcessInfo.
func (in *FoundationDBStatusProcessInfo) DeepCopy() *FoundationDBStatusProcessInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusProcessInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusProcessMessage) DeepCopyInto(out *FoundationDBStatusProcessMessage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusProcessMessage.
func (in *FoundationDBStatusProcessMessage) DeepCopy() *FoundationDBStatusProcessMessage {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusProcessMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusProcessRoleInfo) DeepCopyInto(out *FoundationDBStatusProcessRoleInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusProcessRoleInfo.
func (in *FoundationDBStatusProcessRoleInfo) DeepCopy() *FoundationDBStatusProcessRoleInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusProcessRoleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusQosInfo) DeepCopyInto(out *FoundationDBStatusQosInfo) {
	*out = *in
	out.LimitingDurabilityLagStorageServer = in.LimitingDurabilityLagStorageServer
	out.WorstDataLagStorageServer = in.WorstDataLagStorageServer
	out.WorstDurabilityLagStorageServer = in.WorstDurabilityLagStorageServer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusQosInfo.
func (in *FoundationDBStatusQosInfo) DeepCopy() *FoundationDBStatusQosInfo {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusQosInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusSupportedVersion) DeepCopyInto(out *FoundationDBStatusSupportedVersion) {
	*out = *in
	if in.ConnectedClients != nil {
		in, out := &in.ConnectedClients, &out.ConnectedClients
		*out = make([]FoundationDBStatusConnectedClient, len(*in))
		copy(*out, *in)
	}
	if in.MaxProtocolClients != nil {
		in, out := &in.MaxProtocolClients, &out.MaxProtocolClients
		*out = make([]FoundationDBStatusConnectedClient, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusSupportedVersion.
func (in *FoundationDBStatusSupportedVersion) DeepCopy() *FoundationDBStatusSupportedVersion {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusSupportedVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBStatusTeamTracker) DeepCopyInto(out *FoundationDBStatusTeamTracker) {
	*out = *in
	out.State = in.State
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBStatusTeamTracker.
func (in *FoundationDBStatusTeamTracker) DeepCopy() *FoundationDBStatusTeamTracker {
	if in == nil {
		return nil
	}
	out := new(FoundationDBStatusTeamTracker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationDBUnreachableProcess) DeepCopyInto(out *FoundationDBUnreachableProcess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationDBUnreachableProcess.
func (in *FoundationDBUnreachableProcess) DeepCopy() *FoundationDBUnreachableProcess {
	if in == nil {
		return nil
	}
	out := new(FoundationDBUnreachableProcess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelConfig) DeepCopyInto(out *LabelConfig) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceLabels != nil {
		in, out := &in.ResourceLabels, &out.ResourceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ProcessGroupIDLabels != nil {
		in, out := &in.ProcessGroupIDLabels, &out.ProcessGroupIDLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcessClassLabels != nil {
		in, out := &in.ProcessClassLabels, &out.ProcessClassLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FilterOnOwnerReferences != nil {
		in, out := &in.FilterOnOwnerReferences, &out.FilterOnOwnerReferences
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelConfig.
func (in *LabelConfig) DeepCopy() *LabelConfig {
	if in == nil {
		return nil
	}
	out := new(LabelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LockDenyListEntry) DeepCopyInto(out *LockDenyListEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LockDenyListEntry.
func (in *LockDenyListEntry) DeepCopy() *LockDenyListEntry {
	if in == nil {
		return nil
	}
	out := new(LockDenyListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LockOptions) DeepCopyInto(out *LockOptions) {
	*out = *in
	if in.DisableLocks != nil {
		in, out := &in.DisableLocks, &out.DisableLocks
		*out = new(bool)
		**out = **in
	}
	if in.LockDurationMinutes != nil {
		in, out := &in.LockDurationMinutes, &out.LockDurationMinutes
		*out = new(int)
		**out = **in
	}
	if in.DenyList != nil {
		in, out := &in.DenyList, &out.DenyList
		*out = make([]LockDenyListEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LockOptions.
func (in *LockOptions) DeepCopy() *LockOptions {
	if in == nil {
		return nil
	}
	out := new(LockOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LockSystemStatus) DeepCopyInto(out *LockSystemStatus) {
	*out = *in
	if in.DenyList != nil {
		in, out := &in.DenyList, &out.DenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LockSystemStatus.
func (in *LockSystemStatus) DeepCopy() *LockSystemStatus {
	if in == nil {
		return nil
	}
	out := new(LockSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceModeInfo) DeepCopyInto(out *MaintenanceModeInfo) {
	*out = *in
	if in.StartTimestamp != nil {
		in, out := &in.StartTimestamp, &out.StartTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ProcessGroups != nil {
		in, out := &in.ProcessGroups, &out.ProcessGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceModeInfo.
func (in *MaintenanceModeInfo) DeepCopy() *MaintenanceModeInfo {
	if in == nil {
		return nil
	}
	out := new(MaintenanceModeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceModeOptions) DeepCopyInto(out *MaintenanceModeOptions) {
	*out = *in
	if in.UseMaintenanceModeChecker != nil {
		in, out := &in.UseMaintenanceModeChecker, &out.UseMaintenanceModeChecker
		*out = new(bool)
		**out = **in
	}
	if in.ResetMaintenanceMode != nil {
		in, out := &in.ResetMaintenanceMode, &out.ResetMaintenanceMode
		*out = new(bool)
		**out = **in
	}
	if in.MaintenanceModeTimeSeconds != nil {
		in, out := &in.MaintenanceModeTimeSeconds, &out.MaintenanceModeTimeSeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceModeOptions.
func (in *MaintenanceModeOptions) DeepCopy() *MaintenanceModeOptions {
	if in == nil {
		return nil
	}
	out := new(MaintenanceModeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *None) DeepCopyInto(out *None) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new None.
func (in *None) DeepCopy() *None {
	if in == nil {
		return nil
	}
	out := new(None)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessAddress) DeepCopyInto(out *ProcessAddress) {
	*out = *in
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = make(netx.IP, len(*in))
		copy(*out, *in)
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessAddress.
func (in *ProcessAddress) DeepCopy() *ProcessAddress {
	if in == nil {
		return nil
	}
	out := new(ProcessAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessCounts) DeepCopyInto(out *ProcessCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessCounts.
func (in *ProcessCounts) DeepCopy() *ProcessCounts {
	if in == nil {
		return nil
	}
	out := new(ProcessCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessGroupCondition) DeepCopyInto(out *ProcessGroupCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessGroupCondition.
func (in *ProcessGroupCondition) DeepCopy() *ProcessGroupCondition {
	if in == nil {
		return nil
	}
	out := new(ProcessGroupCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessGroupStatus) DeepCopyInto(out *ProcessGroupStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemovalTimestamp != nil {
		in, out := &in.RemovalTimestamp, &out.RemovalTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ExclusionTimestamp != nil {
		in, out := &in.ExclusionTimestamp, &out.ExclusionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ProcessGroupConditions != nil {
		in, out := &in.ProcessGroupConditions, &out.ProcessGroupConditions
		*out = make([]*ProcessGroupCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProcessGroupCondition)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessGroupStatus.
func (in *ProcessGroupStatus) DeepCopy() *ProcessGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessSettings) DeepCopyInto(out *ProcessSettings) {
	*out = *in
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(corev1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(corev1.PersistentVolumeClaim)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomParameters != nil {
		in, out := &in.CustomParameters, &out.CustomParameters
		*out = make(FoundationDBCustomParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessSettings.
func (in *ProcessSettings) DeepCopy() *ProcessSettings {
	if in == nil {
		return nil
	}
	out := new(ProcessSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryState) DeepCopyInto(out *RecoveryState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryState.
func (in *RecoveryState) DeepCopy() *RecoveryState {
	if in == nil {
		return nil
	}
	out := new(RecoveryState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Region) DeepCopyInto(out *Region) {
	*out = *in
	if in.DataCenters != nil {
		in, out := &in.DataCenters, &out.DataCenters
		*out = make([]DataCenter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Region.
func (in *Region) DeepCopy() *Region {
	if in == nil {
		return nil
	}
	out := new(Region)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredAddressSet) DeepCopyInto(out *RequiredAddressSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredAddressSet.
func (in *RequiredAddressSet) DeepCopy() *RequiredAddressSet {
	if in == nil {
		return nil
	}
	out := new(RequiredAddressSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleCounts) DeepCopyInto(out *RoleCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleCounts.
func (in *RoleCounts) DeepCopy() *RoleCounts {
	if in == nil {
		return nil
	}
	out := new(RoleCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingConfig) DeepCopyInto(out *RoutingConfig) {
	*out = *in
	if in.HeadlessService != nil {
		in, out := &in.HeadlessService, &out.HeadlessService
		*out = new(bool)
		**out = **in
	}
	if in.PublicIPSource != nil {
		in, out := &in.PublicIPSource, &out.PublicIPSource
		*out = new(PublicIPSource)
		**out = **in
	}
	if in.PodIPFamily != nil {
		in, out := &in.PodIPFamily, &out.PodIPFamily
		*out = new(int)
		**out = **in
	}
	if in.UseDNSInClusterFile != nil {
		in, out := &in.UseDNSInClusterFile, &out.UseDNSInClusterFile
		*out = new(bool)
		**out = **in
	}
	if in.DefineDNSLocalityFields != nil {
		in, out := &in.DefineDNSLocalityFields, &out.DefineDNSLocalityFields
		*out = new(bool)
		**out = **in
	}
	if in.DNSDomain != nil {
		in, out := &in.DNSDomain, &out.DNSDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingConfig.
func (in *RoutingConfig) DeepCopy() *RoutingConfig {
	if in == nil {
		return nil
	}
	out := new(RoutingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintReplacementOption) DeepCopyInto(out *TaintReplacementOption) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.DurationInSeconds != nil {
		in, out := &in.DurationInSeconds, &out.DurationInSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintReplacementOption.
func (in *TaintReplacementOption) DeepCopy() *TaintReplacementOption {
	if in == nil {
		return nil
	}
	out := new(TaintReplacementOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Version) DeepCopyInto(out *Version) {
	*out = *in
	out.Version = in.Version
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Version.
func (in *Version) DeepCopy() *Version {
	if in == nil {
		return nil
	}
	out := new(Version)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionFlags) DeepCopyInto(out *VersionFlags) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionFlags.
func (in *VersionFlags) DeepCopy() *VersionFlags {
	if in == nil {
		return nil
	}
	out := new(VersionFlags)
	in.DeepCopyInto(out)
	return out
}
