#!/usr/bin/env bash

set -euo pipefail

if [ $# -eq 0 ]
then
  echo -e "Usage: ./remove_namespaces username [namespace prefix]"
  exit
fi

USERNAME=$1
NAMESPACE=${2:-""}

for ns in $(kubectl get ns --no-headers -o name -l "foundationdb.org/user=$USERNAME,foundationdb.org/testing=chaos" | awk -F/ '{print $2}');
do
  (
    if [ -n "${NAMESPACE}" ] && [[ "${ns}" != "${NAMESPACE}"* ]]
    then
      echo skip deleting namespace "${ns}" owned by "${USERNAME}"
      continue
    fi

    echo "Start deleting namespace ${ns}"
    # Ensure we are deleting the operator deployment first, otherwise it will block the deletion of the namespace
    # by re-adding the finalizer on the backup resource. Wait for 30 seconds to get the namespace and all resources in
    # it deleted. If the timeout is exceeded we still continue.
    kubectl delete ns --ignore-not-found "${ns}" --timeout=30s --grace-period=1 || true
    # Remove the finalizer from the backup resource if present.
    for backup in $(kubectl -n ${ns} get fdbbackup --no-headers -o name);
    do
      echo "Removing finalizer from ${backup} in namespace ${ns}"
      kubectl -n ${ns} patch ${backup} -p '{"metadata":{"finalizers":null}}' --type=merge
    done
    # Remove the finalizer from the pod resource if present.
    for po in $(kubectl -n ${ns} get po --no-headers -o name);
    do
      echo "Removing finalizer from ${po} in namespace ${ns}"
      kubectl -n ${ns} patch ${po} -p '{"metadata":{"finalizers":null}}' --type=merge
    done
  ) &
done
wait

echo "remove all chaos experiments for user"

kubectl -n chaos-testing delete schedules -l "foundationdb.org/user=$USERNAME,foundationdb.org/testing=chaos" --wait=false --ignore-not-found
kubectl -n chaos-testing delete networkchaos -l "foundationdb.org/user=$USERNAME,foundationdb.org/testing=chaos" --wait=false --ignore-not-found
kubectl -n chaos-testing delete iochaos -l "foundationdb.org/user=$USERNAME,foundationdb.org/testing=chaos" --wait=false --ignore-not-found
kubectl -n chaos-testing delete podchaos -l "foundationdb.org/user=$USERNAME,foundationdb.org/testing=chaos" --wait=false --ignore-not-found
kubectl delete clusterrolebinding -l "foundationdb.org/user=$USERNAME,foundationdb.org/testing=chaos" --wait=false --ignore-not-found
kubectl delete clusterrole -l "foundationdb.org/user=$USERNAME,foundationdb.org/testing=chaos" --wait=false --ignore-not-found
