issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  exclude:
    - "ST1000: at least one file in a package should have a package comment"
  exclude-rules:
  # exclude deprecation warning otherwise we get an error for our own deprecations
  - linters:
    - staticcheck
    text: "SA1019:"
  - linters:
    - govet
    text: 'declaration of "(err|ctx)" shadows declaration at'
  - linters:
      - revive
    text: "package-comments: should have a package comment"
  # TODO (johscheuer): Ignore those linting issues for now and change it once we cut a new major release.
  - linters:
      - stylecheck
    text: "ST1003: const StorageEngineRocksDbExperimental"
  - linters:
      - stylecheck
    text: "ST1003: const StorageEngineRocksDbV1"
  # TODO (johscheuer): Fix all go imports to make this check happy, https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1739.
  # - linters:
  #     - depguard
  #   text: "is not allowed from list 'Main'"

linters:
  disable-all: true
  # TODO(johscheuer): activate linters again and fix issues
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
#    - goconst
#    - gocritic
#    - gocyclo
    - gofmt
    #- goimports
    - goprintffuncname
#    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
#    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  errcheck:
    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude: errcheck_excludes.txt
  govet:
    enable:
      - shadow
  staticcheck:
    go: "1.20"
  stylecheck:
    go: "1.20"
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/FoundationDB/fdb-kubernetes-operator
          - github.com/apple/foundationdb
          - github.com/google/go-cmp/cmp
          - sigs.k8s.io/controller-runtime
          - sigs.k8s.io/yaml
          - k8s.io/kubectl
          - k8s.io/apimachinery
          - k8s.io/client-go
          - k8s.io/cli-runtim
          - k8s.io/api
          - k8s.io/klog
          - k8s.io/utils
          - github.com/onsi/gomega
          - github.com/onsi/ginkgo
          - github.com/hashicorp
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/spf13/pflag
          - github.com/fatih/color
          - github.com/chaos-mesh
          - github.com/prometheus
          - github.com/go-logr
run:
  timeout: 10m
  skip-files:
    - "zz_generated.*\\.go$"
  allow-parallel-runners: true
