issues:
  exclude-files:
    - "zz_generated.*\\.go$"
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  exclude:
    - "ST1000: at least one file in a package should have a package comment"
  exclude-rules:
  - path: _test\.go
    linters:
      - revive
    text: "dot-imports: should not use dot imports"
  # exclude deprecation warning otherwise we get an error for our own deprecations
  - linters:
    - staticcheck
    text: "SA1019:"
  - linters:
    - govet
    text: 'declaration of "(err|ctx)" shadows declaration at'
  - linters:
      - revive
    text: "package-comments: should have a package comment"
  # TODO (johscheuer): Ignore those linting issues for now and change it once we cut a new major release.
  - linters:
      - stylecheck
    text: "ST1003: const StorageEngineRocksDbExperimental"
  - linters:
      - stylecheck
    text: "ST1003: const StorageEngineRocksDbV1"

linters:
  disable-all: true
  # TODO(johscheuer): activate linters again and fix issues
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - copyloopvar
#    - goconst
#    - gocritic
#    - gocyclo
    - gofmt
    #- goimports
    - goprintffuncname
#    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
#    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (github.com/FoundationDB/fdb-kubernetes-operator/pkg/fdbadminclient.AdminClient).Close
  govet:
    enable:
      - shadow
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/FoundationDB/fdb-kubernetes-operator
          - github.com/apple/foundationdb
          - github.com/google/go-cmp/cmp
          - sigs.k8s.io/controller-runtime
          - sigs.k8s.io/yaml
          - k8s.io/kubectl
          - k8s.io/apimachinery
          - k8s.io/client-go
          - k8s.io/cli-runtim
          - k8s.io/api
          - k8s.io/klog
          - k8s.io/utils
          - github.com/onsi/gomega
          - github.com/onsi/ginkgo
          - github.com/hashicorp
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/spf13/pflag
          - github.com/fatih/color
          - github.com/chaos-mesh
          - github.com/prometheus
          - github.com/go-logr

run:
  timeout: 10m
  allow-parallel-runners: true
