version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-fdb
    goos:
      - linux
      - windows
      - darwin
    main: ./kubectl-fdb
    binary: kubectl-fdb
    ldflags:
      - -s -w -X github.com/FoundationDB/fdb-kubernetes-operator/v2/kubectl-fdb/cmd.pluginVersion={{ .Version }} -X github.com/FoundationDB/fdb-kubernetes-operator/v2/kubectl-fdb/cmd.pluginBuildDate={{ .Date }} -X github.com/FoundationDB/fdb-kubernetes-operator/v2/kubectl-fdb/cmd.pluginBuildCommit={{ .Commit }}
    goarch:
      - amd64
      - arm64

archives:
  - id: kubectl-fdb
    ids:
      - kubectl-fdb
    formats: [ "binary" ]
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

changelog:
  disable: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"
