apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    app: fdb-kubernetes-operator-controller-manager
spec:
  selector:
    matchLabels:
      app: fdb-kubernetes-operator-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: fdb-kubernetes-operator-controller-manager
    spec:
      initContainers:
        - name: foundationdb-kubernetes-init-6-1
          image: foundationdb/foundationdb-kubernetes-sidecar:6.1.13-1
          args:
            - "--copy-library"
            - "6.1"
            - "--copy-binary"
            - "fdbcli"
            - "--copy-binary"
            - "fdbbackup"
            - "--copy-binary"
            - "fdbrestore"
            - "--output-dir"
            - "/var/output-files/6.1.13"
            - "--init-mode"
          volumeMounts:
            - name: fdb-binaries
              mountPath: /var/output-files
        - name: foundationdb-kubernetes-init-6-2
          image: foundationdb/foundationdb-kubernetes-sidecar:6.2.30-1
          args:
            - "--copy-library"
            - "6.2"
            - "--copy-binary"
            - "fdbcli"
            - "--copy-binary"
            - "fdbbackup"
            - "--copy-binary"
            - "fdbrestore"
            - "--output-dir"
            - "/var/output-files/6.2.30"
            - "--init-mode"
          volumeMounts:
            - name: fdb-binaries
              mountPath: /var/output-files
        - name: foundationdb-kubernetes-init-6-3
          image: foundationdb/foundationdb-kubernetes-sidecar:6.3.10-1
          args:
            - "--copy-library"
            - "6.3"
            - "--copy-binary"
            - "fdbcli"
            - "--copy-binary"
            - "fdbbackup"
            - "--copy-binary"
            - "fdbrestore"
            - "--output-dir"
            - "/var/output-files/6.3.10"
            - "--init-mode"
          volumeMounts:
            - name: fdb-binaries
              mountPath: /var/output-files
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        env:
          - name: FDB_NETWORK_OPTION_EXTERNAL_CLIENT_DIRECTORY
            value: /usr/bin/fdb
        ports:
          - name: metrics
            containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: logs
            mountPath: /var/log/fdb
          - name: fdb-binaries
            mountPath: /usr/bin/fdb
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 4059
        runAsGroup: 4059
        fsGroup: 4059
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: fdb-binaries
          emptyDir: {}
