apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    app: fdb-kubernetes-operator-controller-manager
spec:
  selector:
    matchLabels:
      app: fdb-kubernetes-operator-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: fdb-kubernetes-operator-controller-manager
    spec:
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
          - name: metrics
            containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: logs
            mountPath: /var/log/fdb
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 4059
        runAsGroup: 4059
        fsGroup: 4059
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
