apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fdb-kubernetes-operator
spec:
  selector:
    matchLabels:
      app: fdb-kubernetes-operator-controller-manager
  podMetricsEndpoints:
    - port: metrics
  namespaceSelector:
    any: true
