// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// AutomaticReplacementOptionsApplyConfiguration represents a declarative configuration of the AutomaticReplacementOptions type for use
// with apply.
//
// AutomaticReplacementOptions controls options for automatically replacing
// failed processes.
type AutomaticReplacementOptionsApplyConfiguration struct {
	// Enabled controls whether automatic replacements are enabled.
	// The default is false.
	Enabled *bool `json:"enabled,omitempty"`
	// FaultDomainBasedReplacements controls whether automatic replacements are targeting all failed process groups
	// in a fault domain or only specific Process Groups. If this setting is enabled, the number of different fault
	// domains that can have all their failed process groups replaced at the same time will be equal to MaxConcurrentReplacements.
	// e.g. MaxConcurrentReplacements = 2 would mean that at most 2 different fault domains can have
	// their failed process groups replaced at the same time.
	// The default is false.
	FaultDomainBasedReplacements *bool `json:"faultDomainBasedReplacements,omitempty"`
	// FailureDetectionTimeSeconds controls how long a process must be
	// failed or missing before it is automatically replaced.
	// The default is 7200 seconds, or 2 hours.
	FailureDetectionTimeSeconds *int `json:"failureDetectionTimeSeconds,omitempty"`
	// TaintReplacementTimeSeconds controls how long a pod stays in NodeTaintReplacing condition
	// before it is automatically replaced.
	// The default is 1800 seconds, i.e., 30min
	TaintReplacementTimeSeconds *int `json:"taintReplacementTimeSeconds,omitempty"`
	// MaxConcurrentReplacements controls how many automatic replacements are allowed to take part.
	// This will take the list of current replacements and then calculate the difference between
	// maxConcurrentReplacements and the size of the list. e.g. if currently 3 replacements are
	// queued (e.g. in the processGroupsToRemove list) and maxConcurrentReplacements is 5 the operator
	// is allowed to replace at most 2 process groups. Setting this to 0 will basically disable the automatic
	// replacements.
	MaxConcurrentReplacements *int `json:"maxConcurrentReplacements,omitempty"`
	// TaintReplacementOption controls which taint label the operator will react to.
	TaintReplacementOptions []TaintReplacementOptionApplyConfiguration `json:"taintReplacementOptions,omitempty"`
	// MaxFaultDomainsWithTaintedProcessGroups defines how many fault domains in the cluster can have process groups
	// with the NodeTaintReplacing condition and still allow the operator to automatically replace those process groups.
	// If more fault domains contain process groups with the NodeTaintReplacing condition, the operator will not
	// automatically replace those process groups. This is a safeguard in addition to MaxConcurrentReplacements to make
	// sure the operator is not replacing too many process groups if a large number of nodes are tainted. A absolute number
	// of fault domains or a percentage can be provided.
	// Defaults to 10% of the fault domains or at least 1.
	MaxFaultDomainsWithTaintedProcessGroups *intstr.IntOrString `json:"maxFaultDomainsWithTaintedProcessGroups,omitempty"`
}

// AutomaticReplacementOptionsApplyConfiguration constructs a declarative configuration of the AutomaticReplacementOptions type for use with
// apply.
func AutomaticReplacementOptions() *AutomaticReplacementOptionsApplyConfiguration {
	return &AutomaticReplacementOptionsApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AutomaticReplacementOptionsApplyConfiguration) WithEnabled(value bool) *AutomaticReplacementOptionsApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithFaultDomainBasedReplacements sets the FaultDomainBasedReplacements field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FaultDomainBasedReplacements field is set to the value of the last call.
func (b *AutomaticReplacementOptionsApplyConfiguration) WithFaultDomainBasedReplacements(value bool) *AutomaticReplacementOptionsApplyConfiguration {
	b.FaultDomainBasedReplacements = &value
	return b
}

// WithFailureDetectionTimeSeconds sets the FailureDetectionTimeSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureDetectionTimeSeconds field is set to the value of the last call.
func (b *AutomaticReplacementOptionsApplyConfiguration) WithFailureDetectionTimeSeconds(value int) *AutomaticReplacementOptionsApplyConfiguration {
	b.FailureDetectionTimeSeconds = &value
	return b
}

// WithTaintReplacementTimeSeconds sets the TaintReplacementTimeSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaintReplacementTimeSeconds field is set to the value of the last call.
func (b *AutomaticReplacementOptionsApplyConfiguration) WithTaintReplacementTimeSeconds(value int) *AutomaticReplacementOptionsApplyConfiguration {
	b.TaintReplacementTimeSeconds = &value
	return b
}

// WithMaxConcurrentReplacements sets the MaxConcurrentReplacements field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConcurrentReplacements field is set to the value of the last call.
func (b *AutomaticReplacementOptionsApplyConfiguration) WithMaxConcurrentReplacements(value int) *AutomaticReplacementOptionsApplyConfiguration {
	b.MaxConcurrentReplacements = &value
	return b
}

// WithTaintReplacementOptions adds the given value to the TaintReplacementOptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TaintReplacementOptions field.
func (b *AutomaticReplacementOptionsApplyConfiguration) WithTaintReplacementOptions(values ...*TaintReplacementOptionApplyConfiguration) *AutomaticReplacementOptionsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTaintReplacementOptions")
		}
		b.TaintReplacementOptions = append(b.TaintReplacementOptions, *values[i])
	}
	return b
}

// WithMaxFaultDomainsWithTaintedProcessGroups sets the MaxFaultDomainsWithTaintedProcessGroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxFaultDomainsWithTaintedProcessGroups field is set to the value of the last call.
func (b *AutomaticReplacementOptionsApplyConfiguration) WithMaxFaultDomainsWithTaintedProcessGroups(value intstr.IntOrString) *AutomaticReplacementOptionsApplyConfiguration {
	b.MaxFaultDomainsWithTaintedProcessGroups = &value
	return b
}
