// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupExpirationStatusApplyConfiguration represents a declarative configuration of the BackupExpirationStatus type for use
// with apply.
//
// BackupExpirationStatus records the most recent expiration request and its execution
type BackupExpirationStatusApplyConfiguration struct {
	// BeforeTimestamp is the requested cutoff, not a guarantee that every older file was removed
	BeforeTimestamp *v1.Time `json:"beforeTimestamp,omitempty"`
	// DestinationURL is the backup container pinned when the request was accepted
	DestinationURL *string `json:"destinationURL,omitempty"`
	// ClusterName identifies the source cluster used to resolve the timestamp
	ClusterName *string `json:"clusterName,omitempty"`
	// JobName identifies the Job executing this request
	JobName *string `json:"jobName,omitempty"`
	// Phase reports whether the request is running, succeeded, or failed
	Phase *string `json:"phase,omitempty"`
	// Message provides the Job's failure reason, if any
	Message *string `json:"message,omitempty"`
	// CompletionTime records when the operator observed a terminal Job
	CompletionTime *v1.Time `json:"completionTime,omitempty"`
}

// BackupExpirationStatusApplyConfiguration constructs a declarative configuration of the BackupExpirationStatus type for use with
// apply.
func BackupExpirationStatus() *BackupExpirationStatusApplyConfiguration {
	return &BackupExpirationStatusApplyConfiguration{}
}

// WithBeforeTimestamp sets the BeforeTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BeforeTimestamp field is set to the value of the last call.
func (b *BackupExpirationStatusApplyConfiguration) WithBeforeTimestamp(value v1.Time) *BackupExpirationStatusApplyConfiguration {
	b.BeforeTimestamp = &value
	return b
}

// WithDestinationURL sets the DestinationURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DestinationURL field is set to the value of the last call.
func (b *BackupExpirationStatusApplyConfiguration) WithDestinationURL(value string) *BackupExpirationStatusApplyConfiguration {
	b.DestinationURL = &value
	return b
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *BackupExpirationStatusApplyConfiguration) WithClusterName(value string) *BackupExpirationStatusApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithJobName sets the JobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobName field is set to the value of the last call.
func (b *BackupExpirationStatusApplyConfiguration) WithJobName(value string) *BackupExpirationStatusApplyConfiguration {
	b.JobName = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *BackupExpirationStatusApplyConfiguration) WithPhase(value string) *BackupExpirationStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *BackupExpirationStatusApplyConfiguration) WithMessage(value string) *BackupExpirationStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *BackupExpirationStatusApplyConfiguration) WithCompletionTime(value v1.Time) *BackupExpirationStatusApplyConfiguration {
	b.CompletionTime = &value
	return b
}
