// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// BackupGenerationStatusApplyConfiguration represents a declarative configuration of the BackupGenerationStatus type for use
// with apply.
//
// BackupGenerationStatus stores information on which generations have reached
// different stages in reconciliation for the backup.
type BackupGenerationStatusApplyConfiguration struct {
	// Reconciled provides the last generation that was fully reconciled.
	Reconciled *int64 `json:"reconciled,omitempty"`
	// NeedsBackupAgentUpdate provides the last generation that could not
	// complete reconciliation because the backup agent deployment needs to be
	// updated.
	NeedsBackupAgentUpdate *int64 `json:"needsBackupAgentUpdate,omitempty"`
	// NeedsBackupStart provides the last generation that could not complete
	// reconciliation because we need to start a backup.
	NeedsBackupStart *int64 `json:"needsBackupStart,omitempty"`
	// NeedsBackupStart provides the last generation that could not complete
	// reconciliation because we need to stop a backup.
	NeedsBackupStop *int64 `json:"needsBackupStop,omitempty"`
	// NeedsBackupPauseToggle provides the last generation that needs to have
	// a backup paused or resumed.
	NeedsBackupPauseToggle *int64 `json:"needsBackupPauseToggle,omitempty"`
	// NeedsBackupReconfiguration provides the last generation that could not
	// complete reconciliation because we need to modify backup parameters.
	NeedsBackupReconfiguration *int64 `json:"needsBackupModification,omitempty"`
}

// BackupGenerationStatusApplyConfiguration constructs a declarative configuration of the BackupGenerationStatus type for use with
// apply.
func BackupGenerationStatus() *BackupGenerationStatusApplyConfiguration {
	return &BackupGenerationStatusApplyConfiguration{}
}

// WithReconciled sets the Reconciled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reconciled field is set to the value of the last call.
func (b *BackupGenerationStatusApplyConfiguration) WithReconciled(value int64) *BackupGenerationStatusApplyConfiguration {
	b.Reconciled = &value
	return b
}

// WithNeedsBackupAgentUpdate sets the NeedsBackupAgentUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsBackupAgentUpdate field is set to the value of the last call.
func (b *BackupGenerationStatusApplyConfiguration) WithNeedsBackupAgentUpdate(value int64) *BackupGenerationStatusApplyConfiguration {
	b.NeedsBackupAgentUpdate = &value
	return b
}

// WithNeedsBackupStart sets the NeedsBackupStart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsBackupStart field is set to the value of the last call.
func (b *BackupGenerationStatusApplyConfiguration) WithNeedsBackupStart(value int64) *BackupGenerationStatusApplyConfiguration {
	b.NeedsBackupStart = &value
	return b
}

// WithNeedsBackupStop sets the NeedsBackupStop field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsBackupStop field is set to the value of the last call.
func (b *BackupGenerationStatusApplyConfiguration) WithNeedsBackupStop(value int64) *BackupGenerationStatusApplyConfiguration {
	b.NeedsBackupStop = &value
	return b
}

// WithNeedsBackupPauseToggle sets the NeedsBackupPauseToggle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsBackupPauseToggle field is set to the value of the last call.
func (b *BackupGenerationStatusApplyConfiguration) WithNeedsBackupPauseToggle(value int64) *BackupGenerationStatusApplyConfiguration {
	b.NeedsBackupPauseToggle = &value
	return b
}

// WithNeedsBackupReconfiguration sets the NeedsBackupReconfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsBackupReconfiguration field is set to the value of the last call.
func (b *BackupGenerationStatusApplyConfiguration) WithNeedsBackupReconfiguration(value int64) *BackupGenerationStatusApplyConfiguration {
	b.NeedsBackupReconfiguration = &value
	return b
}
