// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupExpirationApplyConfiguration represents a declarative configuration of the BackupExpiration type for use
// with apply.
//
// BackupExpiration requests expiration of data before a fixed timestamp
type BackupExpirationApplyConfiguration struct {
	// BeforeTimestamp is the expiration cutoff, in RFC3339 format
	// The source cluster must be available to convert this timestamp to an FDB version
	BeforeTimestamp *v1.Time `json:"beforeTimestamp,omitempty"`
}

// BackupExpirationApplyConfiguration constructs a declarative configuration of the BackupExpiration type for use with
// apply.
func BackupExpiration() *BackupExpirationApplyConfiguration {
	return &BackupExpirationApplyConfiguration{}
}

// WithBeforeTimestamp sets the BeforeTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BeforeTimestamp field is set to the value of the last call.
func (b *BackupExpirationApplyConfiguration) WithBeforeTimestamp(value v1.Time) *BackupExpirationApplyConfiguration {
	b.BeforeTimestamp = &value
	return b
}
