// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// BlobStoreConfigurationApplyConfiguration represents a declarative configuration of the BlobStoreConfiguration type for use
// with apply.
//
// BlobStoreConfiguration describes the blob store configuration.
type BlobStoreConfigurationApplyConfiguration struct {
	// The name for the backup.
	// If empty defaults to .metadata.name.
	BackupName *string `json:"backupName,omitempty"`
	// The account name to use with the backup destination.
	// If no port is included, it will default to 443,
	// or 80 if secure_connection URL Parameter is set to 0.
	AccountName *string `json:"accountName,omitempty"`
	// The backup bucket to write to.
	// The default is "fdb-backups".
	Bucket *string `json:"bucket,omitempty"`
	// Additional URL parameters passed to the blobstore URL.
	// See: https://apple.github.io/foundationdb/backups.html#backup-urls
	URLParameters []apiv1beta2.URLParameter `json:"urlParameters,omitempty"`
}

// BlobStoreConfigurationApplyConfiguration constructs a declarative configuration of the BlobStoreConfiguration type for use with
// apply.
func BlobStoreConfiguration() *BlobStoreConfigurationApplyConfiguration {
	return &BlobStoreConfigurationApplyConfiguration{}
}

// WithBackupName sets the BackupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupName field is set to the value of the last call.
func (b *BlobStoreConfigurationApplyConfiguration) WithBackupName(value string) *BlobStoreConfigurationApplyConfiguration {
	b.BackupName = &value
	return b
}

// WithAccountName sets the AccountName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountName field is set to the value of the last call.
func (b *BlobStoreConfigurationApplyConfiguration) WithAccountName(value string) *BlobStoreConfigurationApplyConfiguration {
	b.AccountName = &value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *BlobStoreConfigurationApplyConfiguration) WithBucket(value string) *BlobStoreConfigurationApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithURLParameters adds the given value to the URLParameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the URLParameters field.
func (b *BlobStoreConfigurationApplyConfiguration) WithURLParameters(values ...apiv1beta2.URLParameter) *BlobStoreConfigurationApplyConfiguration {
	for i := range values {
		b.URLParameters = append(b.URLParameters, values[i])
	}
	return b
}
