// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// BuggifyConfigApplyConfiguration represents a declarative configuration of the BuggifyConfig type for use
// with apply.
//
// BuggifyConfig provides options for injecting faults into a cluster for testing.
type BuggifyConfigApplyConfiguration struct {
	// NoSchedule defines a list of process group IDs that should fail to schedule.
	NoSchedule []apiv1beta2.ProcessGroupID `json:"noSchedule,omitempty"`
	// CrashLoops defines a list of process group IDs that should be put into a
	// crash looping state.
	// Deprecated: use CrashLoopContainers instead.
	CrashLoop []apiv1beta2.ProcessGroupID `json:"crashLoop,omitempty"`
	// CrashLoopContainers defines a list of process group IDs and containers
	// that should be put into a crash looping state.
	CrashLoopContainers []CrashLoopContainerObjectApplyConfiguration `json:"crashLoopContainers,omitempty"`
	// EmptyMonitorConf instructs the operator to update all of the fdbmonitor.conf
	// files to have zero fdbserver processes configured.
	EmptyMonitorConf *bool `json:"emptyMonitorConf,omitempty"`
	// IgnoreDuringRestart instructs the operator to ignore the provided process groups IDs during the
	// restart command. This can be useful to simulate cases where the kill command is not restarting all
	// processes. IgnoreDuringRestart does not support the wildcard option to ignore all of this specific cluster processes.
	IgnoreDuringRestart []apiv1beta2.ProcessGroupID `json:"ignoreDuringRestart,omitempty"`
	// BlockRemoval defines a list of process group IDs that will not be removed, even if they are marked for removal.
	// The operator will trigger the exclusion but the removal of the resources will be blocked until they are removed
	// from this list. This setting can be used to simulate cases where a process group is marked for removal but the
	// resources are not yet removed.
	BlockRemoval []apiv1beta2.ProcessGroupID `json:"blockRemoval,omitempty"`
}

// BuggifyConfigApplyConfiguration constructs a declarative configuration of the BuggifyConfig type for use with
// apply.
func BuggifyConfig() *BuggifyConfigApplyConfiguration {
	return &BuggifyConfigApplyConfiguration{}
}

// WithNoSchedule adds the given value to the NoSchedule field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NoSchedule field.
func (b *BuggifyConfigApplyConfiguration) WithNoSchedule(values ...apiv1beta2.ProcessGroupID) *BuggifyConfigApplyConfiguration {
	for i := range values {
		b.NoSchedule = append(b.NoSchedule, values[i])
	}
	return b
}

// WithCrashLoop adds the given value to the CrashLoop field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CrashLoop field.
func (b *BuggifyConfigApplyConfiguration) WithCrashLoop(values ...apiv1beta2.ProcessGroupID) *BuggifyConfigApplyConfiguration {
	for i := range values {
		b.CrashLoop = append(b.CrashLoop, values[i])
	}
	return b
}

// WithCrashLoopContainers adds the given value to the CrashLoopContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CrashLoopContainers field.
func (b *BuggifyConfigApplyConfiguration) WithCrashLoopContainers(values ...*CrashLoopContainerObjectApplyConfiguration) *BuggifyConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCrashLoopContainers")
		}
		b.CrashLoopContainers = append(b.CrashLoopContainers, *values[i])
	}
	return b
}

// WithEmptyMonitorConf sets the EmptyMonitorConf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmptyMonitorConf field is set to the value of the last call.
func (b *BuggifyConfigApplyConfiguration) WithEmptyMonitorConf(value bool) *BuggifyConfigApplyConfiguration {
	b.EmptyMonitorConf = &value
	return b
}

// WithIgnoreDuringRestart adds the given value to the IgnoreDuringRestart field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IgnoreDuringRestart field.
func (b *BuggifyConfigApplyConfiguration) WithIgnoreDuringRestart(values ...apiv1beta2.ProcessGroupID) *BuggifyConfigApplyConfiguration {
	for i := range values {
		b.IgnoreDuringRestart = append(b.IgnoreDuringRestart, values[i])
	}
	return b
}

// WithBlockRemoval adds the given value to the BlockRemoval field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BlockRemoval field.
func (b *BuggifyConfigApplyConfiguration) WithBlockRemoval(values ...apiv1beta2.ProcessGroupID) *BuggifyConfigApplyConfiguration {
	for i := range values {
		b.BlockRemoval = append(b.BlockRemoval, values[i])
	}
	return b
}
