// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// ClusterGenerationStatusApplyConfiguration represents a declarative configuration of the ClusterGenerationStatus type for use
// with apply.
//
// ClusterGenerationStatus stores information on which generations have reached
// different stages in reconciliation for the cluster.
type ClusterGenerationStatusApplyConfiguration struct {
	// Reconciled provides the last generation that was fully reconciled.
	Reconciled *int64 `json:"reconciled,omitempty"`
	// NeedsConfigurationChange provides the last generation that is pending
	// a change to configuration.
	NeedsConfigurationChange *int64 `json:"needsConfigurationChange,omitempty"`
	// NeedsCoordinatorChange provides the last generation that is pending
	// a change to its coordinators.
	NeedsCoordinatorChange *int64 `json:"needsCoordinatorChange,omitempty"`
	// NeedsBounce provides the last generation that is pending a bounce of
	// fdbserver.
	NeedsBounce *int64 `json:"needsBounce,omitempty"`
	// NeedsPodDeletion provides the last generation that is pending pods being
	// deleted and recreated.
	NeedsPodDeletion *int64 `json:"needsPodDeletion,omitempty"`
	// NeedsShrink provides the last generation that is pending pods being
	// excluded and removed.
	NeedsShrink *int64 `json:"needsShrink,omitempty"`
	// NeedsGrow provides the last generation that is pending pods being
	// added.
	NeedsGrow *int64 `json:"needsGrow,omitempty"`
	// NeedsMonitorConfUpdate provides the last generation that needs an update
	// through the fdbmonitor conf.
	NeedsMonitorConfUpdate *int64 `json:"needsMonitorConfUpdate,omitempty"`
	// DatabaseUnavailable provides the last generation that could not
	// complete reconciliation due to the database being unavailable.
	DatabaseUnavailable *int64 `json:"missingDatabaseStatus,omitempty"`
	// HasExtraListeners provides the last generation that could not
	// complete reconciliation because it has more listeners than it is supposed
	// to.
	HasExtraListeners *int64 `json:"hasExtraListeners,omitempty"`
	// NeedsServiceUpdate provides the last generation that needs an update
	// to the service config.
	NeedsServiceUpdate *int64 `json:"needsServiceUpdate,omitempty"`
	// HasPendingRemoval provides the last generation that has pods that have
	// been excluded but are pending being removed.
	//
	// A cluster in this state is considered reconciled, but we track this in
	// the status to allow users of the operator to track when the removal
	// is fully complete.
	HasPendingRemoval *int64 `json:"hasPendingRemoval,omitempty"`
	// HasUnhealthyProcess provides the last generation that has at least one
	// process group with a negative condition.
	HasUnhealthyProcess *int64 `json:"hasUnhealthyProcess,omitempty"`
	// NeedsLockConfigurationChanges provides the last generation that is
	// pending a change to the configuration of the locking system.
	NeedsLockConfigurationChanges *int64 `json:"needsLockConfigurationChanges,omitempty"`
}

// ClusterGenerationStatusApplyConfiguration constructs a declarative configuration of the ClusterGenerationStatus type for use with
// apply.
func ClusterGenerationStatus() *ClusterGenerationStatusApplyConfiguration {
	return &ClusterGenerationStatusApplyConfiguration{}
}

// WithReconciled sets the Reconciled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reconciled field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithReconciled(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.Reconciled = &value
	return b
}

// WithNeedsConfigurationChange sets the NeedsConfigurationChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsConfigurationChange field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsConfigurationChange(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsConfigurationChange = &value
	return b
}

// WithNeedsCoordinatorChange sets the NeedsCoordinatorChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsCoordinatorChange field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsCoordinatorChange(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsCoordinatorChange = &value
	return b
}

// WithNeedsBounce sets the NeedsBounce field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsBounce field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsBounce(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsBounce = &value
	return b
}

// WithNeedsPodDeletion sets the NeedsPodDeletion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsPodDeletion field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsPodDeletion(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsPodDeletion = &value
	return b
}

// WithNeedsShrink sets the NeedsShrink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsShrink field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsShrink(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsShrink = &value
	return b
}

// WithNeedsGrow sets the NeedsGrow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsGrow field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsGrow(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsGrow = &value
	return b
}

// WithNeedsMonitorConfUpdate sets the NeedsMonitorConfUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsMonitorConfUpdate field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsMonitorConfUpdate(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsMonitorConfUpdate = &value
	return b
}

// WithDatabaseUnavailable sets the DatabaseUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DatabaseUnavailable field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithDatabaseUnavailable(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.DatabaseUnavailable = &value
	return b
}

// WithHasExtraListeners sets the HasExtraListeners field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasExtraListeners field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithHasExtraListeners(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.HasExtraListeners = &value
	return b
}

// WithNeedsServiceUpdate sets the NeedsServiceUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsServiceUpdate field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsServiceUpdate(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsServiceUpdate = &value
	return b
}

// WithHasPendingRemoval sets the HasPendingRemoval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasPendingRemoval field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithHasPendingRemoval(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.HasPendingRemoval = &value
	return b
}

// WithHasUnhealthyProcess sets the HasUnhealthyProcess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasUnhealthyProcess field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithHasUnhealthyProcess(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.HasUnhealthyProcess = &value
	return b
}

// WithNeedsLockConfigurationChanges sets the NeedsLockConfigurationChanges field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsLockConfigurationChanges field is set to the value of the last call.
func (b *ClusterGenerationStatusApplyConfiguration) WithNeedsLockConfigurationChanges(value int64) *ClusterGenerationStatusApplyConfiguration {
	b.NeedsLockConfigurationChanges = &value
	return b
}
