// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// ClusterHealthApplyConfiguration represents a declarative configuration of the ClusterHealth type for use
// with apply.
//
// ClusterHealth represents different views into health in the cluster status.
type ClusterHealthApplyConfiguration struct {
	// Available reports whether the database is accepting reads and writes.
	Available *bool `json:"available,omitempty"`
	// Healthy reports whether the database is in a fully healthy state.
	Healthy *bool `json:"healthy,omitempty"`
	// FullReplication reports whether all data are fully replicated according
	// to the current replication policy.
	FullReplication *bool `json:"fullReplication,omitempty"`
	// DataMovementPriority reports the priority of the highest-priority data
	// movement in the cluster.
	DataMovementPriority *int `json:"dataMovementPriority,omitempty"`
}

// ClusterHealthApplyConfiguration constructs a declarative configuration of the ClusterHealth type for use with
// apply.
func ClusterHealth() *ClusterHealthApplyConfiguration {
	return &ClusterHealthApplyConfiguration{}
}

// WithAvailable sets the Available field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Available field is set to the value of the last call.
func (b *ClusterHealthApplyConfiguration) WithAvailable(value bool) *ClusterHealthApplyConfiguration {
	b.Available = &value
	return b
}

// WithHealthy sets the Healthy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Healthy field is set to the value of the last call.
func (b *ClusterHealthApplyConfiguration) WithHealthy(value bool) *ClusterHealthApplyConfiguration {
	b.Healthy = &value
	return b
}

// WithFullReplication sets the FullReplication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullReplication field is set to the value of the last call.
func (b *ClusterHealthApplyConfiguration) WithFullReplication(value bool) *ClusterHealthApplyConfiguration {
	b.FullReplication = &value
	return b
}

// WithDataMovementPriority sets the DataMovementPriority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataMovementPriority field is set to the value of the last call.
func (b *ClusterHealthApplyConfiguration) WithDataMovementPriority(value int) *ClusterHealthApplyConfiguration {
	b.DataMovementPriority = &value
	return b
}
