// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// CoordinatorSelectionSettingApplyConfiguration represents a declarative configuration of the CoordinatorSelectionSetting type for use
// with apply.
//
// CoordinatorSelectionSetting defines the process class and the priority of it.
// A higher priority means that the process class is preferred over another.
type CoordinatorSelectionSettingApplyConfiguration struct {
	// ProcessClass defines the process class to associate with priority with.
	ProcessClass *apiv1beta2.ProcessClass `json:"processClass,omitempty"`
	// Priority defines the ordering of different process classes.
	Priority *int `json:"priority,omitempty"`
}

// CoordinatorSelectionSettingApplyConfiguration constructs a declarative configuration of the CoordinatorSelectionSetting type for use with
// apply.
func CoordinatorSelectionSetting() *CoordinatorSelectionSettingApplyConfiguration {
	return &CoordinatorSelectionSettingApplyConfiguration{}
}

// WithProcessClass sets the ProcessClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessClass field is set to the value of the last call.
func (b *CoordinatorSelectionSettingApplyConfiguration) WithProcessClass(value apiv1beta2.ProcessClass) *CoordinatorSelectionSettingApplyConfiguration {
	b.ProcessClass = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *CoordinatorSelectionSettingApplyConfiguration) WithPriority(value int) *CoordinatorSelectionSettingApplyConfiguration {
	b.Priority = &value
	return b
}
