// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// CrashLoopContainerObjectApplyConfiguration represents a declarative configuration of the CrashLoopContainerObject type for use
// with apply.
//
// CrashLoopContainerObject specifies crash-loop target for specific container.
type CrashLoopContainerObjectApplyConfiguration struct {
	// Name of the target container.
	ContainerName *string `json:"containerName,omitempty"`
	// Target processes to kill inside the container.
	Targets []apiv1beta2.ProcessGroupID `json:"targets,omitempty"`
}

// CrashLoopContainerObjectApplyConfiguration constructs a declarative configuration of the CrashLoopContainerObject type for use with
// apply.
func CrashLoopContainerObject() *CrashLoopContainerObjectApplyConfiguration {
	return &CrashLoopContainerObjectApplyConfiguration{}
}

// WithContainerName sets the ContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerName field is set to the value of the last call.
func (b *CrashLoopContainerObjectApplyConfiguration) WithContainerName(value string) *CrashLoopContainerObjectApplyConfiguration {
	b.ContainerName = &value
	return b
}

// WithTargets adds the given value to the Targets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Targets field.
func (b *CrashLoopContainerObjectApplyConfiguration) WithTargets(values ...apiv1beta2.ProcessGroupID) *CrashLoopContainerObjectApplyConfiguration {
	for i := range values {
		b.Targets = append(b.Targets, values[i])
	}
	return b
}
