// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// DatabaseConfigurationApplyConfiguration represents a declarative configuration of the DatabaseConfiguration type for use
// with apply.
//
// DatabaseConfiguration represents the configuration of the database
type DatabaseConfigurationApplyConfiguration struct {
	// RedundancyMode defines the core replication factor for the database.
	RedundancyMode *apiv1beta2.RedundancyMode `json:"redundancy_mode,omitempty"`
	// StorageEngine defines the storage engine the database uses.
	StorageEngine *apiv1beta2.StorageEngine `json:"storage_engine,omitempty"`
	// UsableRegions defines how many regions the database should store data in.
	UsableRegions *int `json:"usable_regions,omitempty"`
	// Regions defines the regions that the database can replicate in.
	Regions []RegionApplyConfiguration `json:"regions,omitempty"`
	// ExcludedServers defines the list  of excluded servers form the database.
	ExcludedServers []ExcludedServersApplyConfiguration `json:"excluded_servers,omitempty"`
	// StorageMigrationType defines the storage migration type.
	StorageMigrationType *apiv1beta2.StorageMigrationType `json:"storage_migration_type,omitempty"`
	// PerpetualStorageWiggle defines the wiggle speed. If set to 0 this feature is disabled.
	// When setting StorageMigrationType to StorageMigrationTypeGradual, this value must be greater
	// than 0.
	PerpetualStorageWiggle *int `json:"perpetual_storage_wiggle,omitempty"`
	// PerpetualStorageWiggleLocality if defined the specified locality will be migrated.
	// Format is: <<LOCALITY_KEY>:<LOCALITY_VALUE>|0>
	PerpetualStorageWiggleLocality *string `json:"perpetual_storage_wiggle_locality,omitempty"`
	// PerpetualStorageWiggleEngine defines the perpetual storage engine type.
	PerpetualStorageWiggleEngine *apiv1beta2.StorageEngine `json:"perpetual_storage_wiggle_engine,omitempty"`
}

// DatabaseConfigurationApplyConfiguration constructs a declarative configuration of the DatabaseConfiguration type for use with
// apply.
func DatabaseConfiguration() *DatabaseConfigurationApplyConfiguration {
	return &DatabaseConfigurationApplyConfiguration{}
}

// WithRedundancyMode sets the RedundancyMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedundancyMode field is set to the value of the last call.
func (b *DatabaseConfigurationApplyConfiguration) WithRedundancyMode(value apiv1beta2.RedundancyMode) *DatabaseConfigurationApplyConfiguration {
	b.RedundancyMode = &value
	return b
}

// WithStorageEngine sets the StorageEngine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageEngine field is set to the value of the last call.
func (b *DatabaseConfigurationApplyConfiguration) WithStorageEngine(value apiv1beta2.StorageEngine) *DatabaseConfigurationApplyConfiguration {
	b.StorageEngine = &value
	return b
}

// WithUsableRegions sets the UsableRegions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsableRegions field is set to the value of the last call.
func (b *DatabaseConfigurationApplyConfiguration) WithUsableRegions(value int) *DatabaseConfigurationApplyConfiguration {
	b.UsableRegions = &value
	return b
}

// WithRegions adds the given value to the Regions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Regions field.
func (b *DatabaseConfigurationApplyConfiguration) WithRegions(values ...*RegionApplyConfiguration) *DatabaseConfigurationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRegions")
		}
		b.Regions = append(b.Regions, *values[i])
	}
	return b
}

// WithExcludedServers adds the given value to the ExcludedServers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludedServers field.
func (b *DatabaseConfigurationApplyConfiguration) WithExcludedServers(values ...*ExcludedServersApplyConfiguration) *DatabaseConfigurationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExcludedServers")
		}
		b.ExcludedServers = append(b.ExcludedServers, *values[i])
	}
	return b
}

// WithStorageMigrationType sets the StorageMigrationType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageMigrationType field is set to the value of the last call.
func (b *DatabaseConfigurationApplyConfiguration) WithStorageMigrationType(value apiv1beta2.StorageMigrationType) *DatabaseConfigurationApplyConfiguration {
	b.StorageMigrationType = &value
	return b
}

// WithPerpetualStorageWiggle sets the PerpetualStorageWiggle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerpetualStorageWiggle field is set to the value of the last call.
func (b *DatabaseConfigurationApplyConfiguration) WithPerpetualStorageWiggle(value int) *DatabaseConfigurationApplyConfiguration {
	b.PerpetualStorageWiggle = &value
	return b
}

// WithPerpetualStorageWiggleLocality sets the PerpetualStorageWiggleLocality field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerpetualStorageWiggleLocality field is set to the value of the last call.
func (b *DatabaseConfigurationApplyConfiguration) WithPerpetualStorageWiggleLocality(value string) *DatabaseConfigurationApplyConfiguration {
	b.PerpetualStorageWiggleLocality = &value
	return b
}

// WithPerpetualStorageWiggleEngine sets the PerpetualStorageWiggleEngine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerpetualStorageWiggleEngine field is set to the value of the last call.
func (b *DatabaseConfigurationApplyConfiguration) WithPerpetualStorageWiggleEngine(value apiv1beta2.StorageEngine) *DatabaseConfigurationApplyConfiguration {
	b.PerpetualStorageWiggleEngine = &value
	return b
}
