// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// FoundationDBBackupSpecApplyConfiguration represents a declarative configuration of the FoundationDBBackupSpec type for use
// with apply.
//
// FoundationDBBackupSpec describes the desired state of the backup for a cluster.
type FoundationDBBackupSpecApplyConfiguration struct {
	// The version of FoundationDB that the backup agents should run.
	Version *string `json:"version,omitempty"`
	// The cluster this backup is for.
	ClusterName *string `json:"clusterName,omitempty"`
	// DataCenter defines the data center where these processes are running.
	DataCenter *string `json:"dataCenter,omitempty"`
	// The desired state of the backup.
	// The default is Running.
	BackupState *apiv1beta2.BackupState `json:"backupState,omitempty"`
	// AgentCount defines the number of backup agents to run.
	// The default is run 2 agents.
	AgentCount *int `json:"agentCount,omitempty"`
	// The time window between new snapshots.
	// This is measured in seconds. The default is 864,000, or 10 days.
	SnapshotPeriodSeconds *int `json:"snapshotPeriodSeconds,omitempty"`
	// BackupDeploymentMetadata allows customizing labels and annotations on the
	// deployment for the backup agents.
	BackupDeploymentMetadata *v1.ObjectMetaApplyConfiguration `json:"backupDeploymentMetadata,omitempty"`
	// PodTemplateSpec allows customizing the pod template for the backup
	// agents.
	PodTemplateSpec *corev1.PodTemplateSpec `json:"podTemplateSpec,omitempty"`
	// CustomParameters defines additional parameters to pass to the backup
	// agents.
	CustomParameters *apiv1beta2.FoundationDBCustomParameters `json:"customParameters,omitempty"`
	// This setting defines if a user provided image can have it's own tag
	// rather than getting the provided version appended.
	// You have to ensure that the specified version in the Spec is compatible
	// with the given version in your custom image.
	// Deprecated: use ImageConfigs instead.
	AllowTagOverride *bool `json:"allowTagOverride,omitempty"`
	// This is the configuration of the target blobstore for this backup.
	BlobStoreConfiguration *BlobStoreConfigurationApplyConfiguration `json:"blobStoreConfiguration,omitempty"`
	// The path to the encryption key used to encrypt the backup. This feature is only supported in FDB versions 7.4.6
	// or newer. Older versions will not use this flag.
	EncryptionKeyPath *string `json:"encryptionKeyPath,omitempty"`
	// MainContainer defines customization for the foundationdb container.
	// Note: The enableTls setting is ignored for backup agents - use TLS environment variables instead.
	MainContainer *ContainerOverridesApplyConfiguration `json:"mainContainer,omitempty"`
	// SidecarContainer defines customization for the
	// foundationdb-kubernetes-sidecar container.
	SidecarContainer *ContainerOverridesApplyConfiguration `json:"sidecarContainer,omitempty"`
	// ImageType defines the image type that should be used for the FoundationDBCluster deployment. When the type
	// is set to "unified" the deployment will use the new fdb-kubernetes-monitor. Otherwise the main container and
	// the sidecar container will use different images.
	// Default: split
	ImageType *apiv1beta2.ImageType `json:"imageType,omitempty"`
	// BackupType defines the backup type that should be used for the backup. When the BackupType is set to
	// BackupTypePartitionedLog, it's expected that the FoundationDBCluster creates and manages the additional
	// backup worker processes. A migration to a different backup type is not yet supported in the operator.
	// Default: "backup_agent".
	BackupType *apiv1beta2.BackupType `json:"backupType,omitempty"`
	// DeletionPolicy defines the deletion policy for this backup. The BackupDeletionPolicy defines the actions
	// that should be taken when the FoundationDBBackup resource has a deletion timestamp.
	DeletionPolicy *apiv1beta2.BackupDeletionPolicy `json:"deletionPolicy,omitempty"`
	// BackupMode defines the backup mode that should be used for the backup. When the BackupMode is set to
	// BackupModeOneTime, the backup will create a single snapshot and then stop. When set to BackupModeContinuous,
	// the backup will run continuously, creating snapshots at regular intervals defined by SnapshotPeriodSeconds.
	// Default: "Continuous".
	BackupMode *apiv1beta2.BackupMode `json:"backupMode,omitempty"`
}

// FoundationDBBackupSpecApplyConfiguration constructs a declarative configuration of the FoundationDBBackupSpec type for use with
// apply.
func FoundationDBBackupSpec() *FoundationDBBackupSpecApplyConfiguration {
	return &FoundationDBBackupSpecApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithVersion(value string) *FoundationDBBackupSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithClusterName(value string) *FoundationDBBackupSpecApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithDataCenter sets the DataCenter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataCenter field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithDataCenter(value string) *FoundationDBBackupSpecApplyConfiguration {
	b.DataCenter = &value
	return b
}

// WithBackupState sets the BackupState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupState field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithBackupState(value apiv1beta2.BackupState) *FoundationDBBackupSpecApplyConfiguration {
	b.BackupState = &value
	return b
}

// WithAgentCount sets the AgentCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentCount field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithAgentCount(value int) *FoundationDBBackupSpecApplyConfiguration {
	b.AgentCount = &value
	return b
}

// WithSnapshotPeriodSeconds sets the SnapshotPeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotPeriodSeconds field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithSnapshotPeriodSeconds(value int) *FoundationDBBackupSpecApplyConfiguration {
	b.SnapshotPeriodSeconds = &value
	return b
}

// WithBackupDeploymentMetadata sets the BackupDeploymentMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupDeploymentMetadata field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithBackupDeploymentMetadata(value *v1.ObjectMetaApplyConfiguration) *FoundationDBBackupSpecApplyConfiguration {
	b.BackupDeploymentMetadata = value
	return b
}

// WithPodTemplateSpec sets the PodTemplateSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplateSpec field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithPodTemplateSpec(value corev1.PodTemplateSpec) *FoundationDBBackupSpecApplyConfiguration {
	b.PodTemplateSpec = &value
	return b
}

// WithCustomParameters sets the CustomParameters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomParameters field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithCustomParameters(value apiv1beta2.FoundationDBCustomParameters) *FoundationDBBackupSpecApplyConfiguration {
	b.CustomParameters = &value
	return b
}

// WithAllowTagOverride sets the AllowTagOverride field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowTagOverride field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithAllowTagOverride(value bool) *FoundationDBBackupSpecApplyConfiguration {
	b.AllowTagOverride = &value
	return b
}

// WithBlobStoreConfiguration sets the BlobStoreConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlobStoreConfiguration field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithBlobStoreConfiguration(value *BlobStoreConfigurationApplyConfiguration) *FoundationDBBackupSpecApplyConfiguration {
	b.BlobStoreConfiguration = value
	return b
}

// WithEncryptionKeyPath sets the EncryptionKeyPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EncryptionKeyPath field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithEncryptionKeyPath(value string) *FoundationDBBackupSpecApplyConfiguration {
	b.EncryptionKeyPath = &value
	return b
}

// WithMainContainer sets the MainContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainContainer field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithMainContainer(value *ContainerOverridesApplyConfiguration) *FoundationDBBackupSpecApplyConfiguration {
	b.MainContainer = value
	return b
}

// WithSidecarContainer sets the SidecarContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarContainer field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithSidecarContainer(value *ContainerOverridesApplyConfiguration) *FoundationDBBackupSpecApplyConfiguration {
	b.SidecarContainer = value
	return b
}

// WithImageType sets the ImageType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageType field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithImageType(value apiv1beta2.ImageType) *FoundationDBBackupSpecApplyConfiguration {
	b.ImageType = &value
	return b
}

// WithBackupType sets the BackupType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupType field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithBackupType(value apiv1beta2.BackupType) *FoundationDBBackupSpecApplyConfiguration {
	b.BackupType = &value
	return b
}

// WithDeletionPolicy sets the DeletionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionPolicy field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithDeletionPolicy(value apiv1beta2.BackupDeletionPolicy) *FoundationDBBackupSpecApplyConfiguration {
	b.DeletionPolicy = &value
	return b
}

// WithBackupMode sets the BackupMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupMode field is set to the value of the last call.
func (b *FoundationDBBackupSpecApplyConfiguration) WithBackupMode(value apiv1beta2.BackupMode) *FoundationDBBackupSpecApplyConfiguration {
	b.BackupMode = &value
	return b
}
