// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// FoundationDBClusterFaultDomainApplyConfiguration represents a declarative configuration of the FoundationDBClusterFaultDomain type for use
// with apply.
//
// FoundationDBClusterFaultDomain describes the fault domain that a cluster is
// replicated across.
type FoundationDBClusterFaultDomainApplyConfiguration struct {
	// Key provides a topology key for the fault domain to replicate across.
	Key *string `json:"key,omitempty"`
	// Value provides a hardcoded value to use for the zoneid for the pods.
	Value *string `json:"value,omitempty"`
	// ValueFrom provides a field selector to use as the source of the fault
	// domain.
	ValueFrom *string `json:"valueFrom,omitempty"`
	// ZoneCount provides the number of fault domains in the data center where
	// these processes are running. This is only used in the
	// `kubernetes-cluster` fault domain strategy.
	ZoneCount *int `json:"zoneCount,omitempty"`
	// ZoneIndex provides the index of this Kubernetes cluster in the list of
	// KCs in the data center. This is only used in the `kubernetes-cluster`
	// fault domain strategy.
	ZoneIndex *int `json:"zoneIndex,omitempty"`
}

// FoundationDBClusterFaultDomainApplyConfiguration constructs a declarative configuration of the FoundationDBClusterFaultDomain type for use with
// apply.
func FoundationDBClusterFaultDomain() *FoundationDBClusterFaultDomainApplyConfiguration {
	return &FoundationDBClusterFaultDomainApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *FoundationDBClusterFaultDomainApplyConfiguration) WithKey(value string) *FoundationDBClusterFaultDomainApplyConfiguration {
	b.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *FoundationDBClusterFaultDomainApplyConfiguration) WithValue(value string) *FoundationDBClusterFaultDomainApplyConfiguration {
	b.Value = &value
	return b
}

// WithValueFrom sets the ValueFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueFrom field is set to the value of the last call.
func (b *FoundationDBClusterFaultDomainApplyConfiguration) WithValueFrom(value string) *FoundationDBClusterFaultDomainApplyConfiguration {
	b.ValueFrom = &value
	return b
}

// WithZoneCount sets the ZoneCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneCount field is set to the value of the last call.
func (b *FoundationDBClusterFaultDomainApplyConfiguration) WithZoneCount(value int) *FoundationDBClusterFaultDomainApplyConfiguration {
	b.ZoneCount = &value
	return b
}

// WithZoneIndex sets the ZoneIndex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneIndex field is set to the value of the last call.
func (b *FoundationDBClusterFaultDomainApplyConfiguration) WithZoneIndex(value int) *FoundationDBClusterFaultDomainApplyConfiguration {
	b.ZoneIndex = &value
	return b
}
