// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// FoundationDBRestoreSpecApplyConfiguration represents a declarative configuration of the FoundationDBRestoreSpec type for use
// with apply.
//
// FoundationDBRestoreSpec describes the desired state of the backup for a cluster.
type FoundationDBRestoreSpecApplyConfiguration struct {
	// DestinationClusterName provides the name of the cluster that the data is
	// being restored into.
	DestinationClusterName *string `json:"destinationClusterName,omitempty"`
	// The key ranges to restore.
	KeyRanges []FoundationDBKeyRangeApplyConfiguration `json:"keyRanges,omitempty"`
	// This is the configuration of the target blobstore for this backup.
	BlobStoreConfiguration *BlobStoreConfigurationApplyConfiguration `json:"blobStoreConfiguration,omitempty"`
	// CustomParameters defines additional parameters to pass to the backup
	// agents.
	CustomParameters *apiv1beta2.FoundationDBCustomParameters `json:"customParameters,omitempty"`
	// The path to the encryption key used to encrypt the backup.
	EncryptionKeyPath *string `json:"encryptionKeyPath,omitempty"`
	// Instead of the latest version the backup can be restored to, restore to the specified version.
	BackupVersion *uint64 `json:"backupVersion,omitempty"`
}

// FoundationDBRestoreSpecApplyConfiguration constructs a declarative configuration of the FoundationDBRestoreSpec type for use with
// apply.
func FoundationDBRestoreSpec() *FoundationDBRestoreSpecApplyConfiguration {
	return &FoundationDBRestoreSpecApplyConfiguration{}
}

// WithDestinationClusterName sets the DestinationClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DestinationClusterName field is set to the value of the last call.
func (b *FoundationDBRestoreSpecApplyConfiguration) WithDestinationClusterName(value string) *FoundationDBRestoreSpecApplyConfiguration {
	b.DestinationClusterName = &value
	return b
}

// WithKeyRanges adds the given value to the KeyRanges field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the KeyRanges field.
func (b *FoundationDBRestoreSpecApplyConfiguration) WithKeyRanges(values ...*FoundationDBKeyRangeApplyConfiguration) *FoundationDBRestoreSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithKeyRanges")
		}
		b.KeyRanges = append(b.KeyRanges, *values[i])
	}
	return b
}

// WithBlobStoreConfiguration sets the BlobStoreConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlobStoreConfiguration field is set to the value of the last call.
func (b *FoundationDBRestoreSpecApplyConfiguration) WithBlobStoreConfiguration(value *BlobStoreConfigurationApplyConfiguration) *FoundationDBRestoreSpecApplyConfiguration {
	b.BlobStoreConfiguration = value
	return b
}

// WithCustomParameters sets the CustomParameters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomParameters field is set to the value of the last call.
func (b *FoundationDBRestoreSpecApplyConfiguration) WithCustomParameters(value apiv1beta2.FoundationDBCustomParameters) *FoundationDBRestoreSpecApplyConfiguration {
	b.CustomParameters = &value
	return b
}

// WithEncryptionKeyPath sets the EncryptionKeyPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EncryptionKeyPath field is set to the value of the last call.
func (b *FoundationDBRestoreSpecApplyConfiguration) WithEncryptionKeyPath(value string) *FoundationDBRestoreSpecApplyConfiguration {
	b.EncryptionKeyPath = &value
	return b
}

// WithBackupVersion sets the BackupVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupVersion field is set to the value of the last call.
func (b *FoundationDBRestoreSpecApplyConfiguration) WithBackupVersion(value uint64) *FoundationDBRestoreSpecApplyConfiguration {
	b.BackupVersion = &value
	return b
}
