// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	time "time"

	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// FoundationDBClusterAutomationOptionsApplyConfiguration represents a declarative configuration of the FoundationDBClusterAutomationOptions type for use
// with apply.
//
// FoundationDBClusterAutomationOptions provides flags for enabling or disabling
// operations that can be performed on a cluster.
type FoundationDBClusterAutomationOptionsApplyConfiguration struct {
	// ConfigureDatabase defines whether the operator is allowed to reconfigure
	// the database.
	ConfigureDatabase *bool `json:"configureDatabase,omitempty"`
	// KillProcesses defines whether the operator is allowed to bounce fdbserver
	// processes.
	KillProcesses *bool `json:"killProcesses,omitempty"`
	// CacheDatabaseStatusForReconciliation defines whether the operator is using the same FoundationDB machine-readable
	// status for all sub-reconcilers or if the machine-readable status should be fetched by ever sub-reconciler if
	// required. Enabling this setting might improve the operator reconciliation speed for large clusters.
	CacheDatabaseStatusForReconciliation *bool `json:"cacheDatabaseStatusForReconciliation,omitempty"`
	// Replacements contains options for automatically replacing failed
	// processes.
	Replacements *AutomaticReplacementOptionsApplyConfiguration `json:"replacements,omitempty"`
	// IgnorePendingPodsDuration defines how long a Pod has to be in the Pending Phase before
	// ignore it during reconciliation. This prevents Pod that are stuck in Pending to block
	// further reconciliation.
	IgnorePendingPodsDuration *time.Duration `json:"ignorePendingPodsDuration,omitempty"`
	// UseNonBlockingExcludes defines whether the operator is allowed to use non blocking exclude commands.
	// The default is false.
	UseNonBlockingExcludes *bool `json:"useNonBlockingExcludes,omitempty"`
	// UseLocalitiesForExclusion defines whether the exclusions are done using localities instead of IP addresses. This
	// feature requires at least FDB 7.1.42 or 7.3.26.
	// The default is false.
	UseLocalitiesForExclusion *bool `json:"useLocalitiesForExclusion,omitempty"`
	// IgnoreTerminatingPodsSeconds defines how long a Pod has to be in the Terminating Phase before
	// we ignore it during reconciliation. This prevents Pod that are stuck in Terminating to block
	// further reconciliation.
	IgnoreTerminatingPodsSeconds *int `json:"ignoreTerminatingPodsSeconds,omitempty"`
	// IgnoreMissingProcessesSeconds defines how long a process group has to be in the MissingProcess condition until
	// it will be ignored during reconciliation. This prevents that a process will block reconciliation.
	IgnoreMissingProcessesSeconds *int `json:"ignoreMissingProcessesSeconds,omitempty"`
	// FailedPodDurationSeconds defines the duration a Pod can stay in the deleted state (deletionTimestamp != 0) before
	// it gets marked as PodFailed. This is important in cases where a fdbserver process is still reporting but the
	// Pod resource is marked for deletion. This can happen when the kubelet or a node fails. Setting this condition
	// will ensure that the operator is replacing affected Pods.
	FailedPodDurationSeconds *int `json:"failedPodDurationSeconds,omitempty"`
	// MaxConcurrentReplacements defines how many process groups can be concurrently
	// replaced if they are misconfigured. If the value will be set to 0 this will block replacements
	// and these misconfigured Pods must be replaced manually or by another process. For each reconcile
	// loop the operator calculates the maximum number of possible replacements by taken this value as the
	// upper limit and removes all ongoing replacements that have not finished. Which means if the value is
	// set to 5 and we have 4 ongoing replacements (process groups marked with remove but not excluded) the
	// operator is allowed to replace on further process group.
	MaxConcurrentReplacements *int `json:"maxConcurrentReplacements,omitempty"`
	// DeletionMode defines the deletion mode for this cluster. This can be
	// PodUpdateModeNone, PodUpdateModeAll, PodUpdateModeZone or PodUpdateModeProcessGroup. The
	// DeletionMode defines how Pods are deleted in order to update them or
	// when they are removed.
	DeletionMode *apiv1beta2.PodUpdateMode `json:"deletionMode,omitempty"`
	// RemovalMode defines the removal mode for this cluster. This can be
	// PodUpdateModeNone, PodUpdateModeAll, PodUpdateModeZone or PodUpdateModeProcessGroup. The
	// RemovalMode defines how process groups are deleted in order when they
	// are marked for removal.
	RemovalMode *apiv1beta2.PodUpdateMode `json:"removalMode,omitempty"`
	// WaitBetweenRemovalsSeconds defines how long to wait between the last removal and the next removal. This is only an
	// upper limit if the process group and the according resources are deleted faster than the provided duration the
	// operator will move on with the next removal. The idea is to prevent a race condition were the operator deletes
	// a resource but the Kubernetes API is slower to trigger the actual deletion, and we are running into a situation
	// where the fault tolerance check still includes the already deleted processes.
	// Defaults to 60.
	WaitBetweenRemovalsSeconds *int `json:"waitBetweenRemovalsSeconds,omitempty"`
	// PodUpdateStrategy defines how Pod spec changes are rolled out either by replacing Pods or by deleting Pods.
	// The default for this is ReplaceTransactionSystem.
	PodUpdateStrategy *apiv1beta2.PodUpdateStrategy `json:"podUpdateStrategy,omitempty"`
	// UseManagementAPI defines if the operator should make use of the management API instead of
	// using fdbcli to interact with the FoundationDB cluster.
	// Deprecated: Use DatabaseInteractionMode instead.
	UseManagementAPI *bool `json:"useManagementAPI,omitempty"`
	// MaintenanceModeOptions contains options for maintenance mode related settings.
	MaintenanceModeOptions *MaintenanceModeOptionsApplyConfiguration `json:"maintenanceModeOptions,omitempty"`
	// IgnoreLogGroupsForUpgrade defines the list of LogGroups that should be ignored during fdb version upgrade.
	// The default is a list that includes "fdb-kubernetes-operator".
	IgnoreLogGroupsForUpgrade []apiv1beta2.LogGroup `json:"ignoreLogGroupsForUpgrade,omitempty"`
	// SynchronizationMode defines the synchronization mode for clusters that are managed by multiple operator instances.
	// The default is "local" which means all operator instances are only acting on their local processes, with the exception for
	// cluster upgrades. In the "global" mode the operator instances coordinate actions to only issue a single
	// exclude/bounce/include to reduce the disruptions. The global coordination mode is based on an optimistic mode
	// and there are no guarantees that the action will only be executed once, e.g. because of a slow operator instance.
	//
	// More details:
	// https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/design/better_coordination_multi_operator.md
	SynchronizationMode *string `json:"synchronizationMode,omitempty"`
	// DatabaseInteractionMode defines how the operator should interact with the FDB cluster. Possible options right now
	// are "fdbcli", which is the default way and "managementapi" which will make use of the management module in FDB:
	// https://apple.github.io/foundationdb/special-keys.html#management-module.
	DatabaseInteractionMode *apiv1beta2.DatabaseInteractionMode `json:"databaseInteractionMode,omitempty"`
}

// FoundationDBClusterAutomationOptionsApplyConfiguration constructs a declarative configuration of the FoundationDBClusterAutomationOptions type for use with
// apply.
func FoundationDBClusterAutomationOptions() *FoundationDBClusterAutomationOptionsApplyConfiguration {
	return &FoundationDBClusterAutomationOptionsApplyConfiguration{}
}

// WithConfigureDatabase sets the ConfigureDatabase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigureDatabase field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithConfigureDatabase(value bool) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.ConfigureDatabase = &value
	return b
}

// WithKillProcesses sets the KillProcesses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KillProcesses field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithKillProcesses(value bool) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.KillProcesses = &value
	return b
}

// WithCacheDatabaseStatusForReconciliation sets the CacheDatabaseStatusForReconciliation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheDatabaseStatusForReconciliation field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithCacheDatabaseStatusForReconciliation(value bool) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.CacheDatabaseStatusForReconciliation = &value
	return b
}

// WithReplacements sets the Replacements field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replacements field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithReplacements(value *AutomaticReplacementOptionsApplyConfiguration) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.Replacements = value
	return b
}

// WithIgnorePendingPodsDuration sets the IgnorePendingPodsDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnorePendingPodsDuration field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithIgnorePendingPodsDuration(value time.Duration) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.IgnorePendingPodsDuration = &value
	return b
}

// WithUseNonBlockingExcludes sets the UseNonBlockingExcludes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseNonBlockingExcludes field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithUseNonBlockingExcludes(value bool) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.UseNonBlockingExcludes = &value
	return b
}

// WithUseLocalitiesForExclusion sets the UseLocalitiesForExclusion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseLocalitiesForExclusion field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithUseLocalitiesForExclusion(value bool) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.UseLocalitiesForExclusion = &value
	return b
}

// WithIgnoreTerminatingPodsSeconds sets the IgnoreTerminatingPodsSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreTerminatingPodsSeconds field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithIgnoreTerminatingPodsSeconds(value int) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.IgnoreTerminatingPodsSeconds = &value
	return b
}

// WithIgnoreMissingProcessesSeconds sets the IgnoreMissingProcessesSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreMissingProcessesSeconds field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithIgnoreMissingProcessesSeconds(value int) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.IgnoreMissingProcessesSeconds = &value
	return b
}

// WithFailedPodDurationSeconds sets the FailedPodDurationSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedPodDurationSeconds field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithFailedPodDurationSeconds(value int) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.FailedPodDurationSeconds = &value
	return b
}

// WithMaxConcurrentReplacements sets the MaxConcurrentReplacements field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConcurrentReplacements field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithMaxConcurrentReplacements(value int) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.MaxConcurrentReplacements = &value
	return b
}

// WithDeletionMode sets the DeletionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionMode field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithDeletionMode(value apiv1beta2.PodUpdateMode) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.DeletionMode = &value
	return b
}

// WithRemovalMode sets the RemovalMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemovalMode field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithRemovalMode(value apiv1beta2.PodUpdateMode) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.RemovalMode = &value
	return b
}

// WithWaitBetweenRemovalsSeconds sets the WaitBetweenRemovalsSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WaitBetweenRemovalsSeconds field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithWaitBetweenRemovalsSeconds(value int) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.WaitBetweenRemovalsSeconds = &value
	return b
}

// WithPodUpdateStrategy sets the PodUpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodUpdateStrategy field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithPodUpdateStrategy(value apiv1beta2.PodUpdateStrategy) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.PodUpdateStrategy = &value
	return b
}

// WithUseManagementAPI sets the UseManagementAPI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseManagementAPI field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithUseManagementAPI(value bool) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.UseManagementAPI = &value
	return b
}

// WithMaintenanceModeOptions sets the MaintenanceModeOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceModeOptions field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithMaintenanceModeOptions(value *MaintenanceModeOptionsApplyConfiguration) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.MaintenanceModeOptions = value
	return b
}

// WithIgnoreLogGroupsForUpgrade adds the given value to the IgnoreLogGroupsForUpgrade field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IgnoreLogGroupsForUpgrade field.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithIgnoreLogGroupsForUpgrade(values ...apiv1beta2.LogGroup) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	for i := range values {
		b.IgnoreLogGroupsForUpgrade = append(b.IgnoreLogGroupsForUpgrade, values[i])
	}
	return b
}

// WithSynchronizationMode sets the SynchronizationMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SynchronizationMode field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithSynchronizationMode(value string) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.SynchronizationMode = &value
	return b
}

// WithDatabaseInteractionMode sets the DatabaseInteractionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DatabaseInteractionMode field is set to the value of the last call.
func (b *FoundationDBClusterAutomationOptionsApplyConfiguration) WithDatabaseInteractionMode(value apiv1beta2.DatabaseInteractionMode) *FoundationDBClusterAutomationOptionsApplyConfiguration {
	b.DatabaseInteractionMode = &value
	return b
}
