// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// FoundationDBKeyRangeApplyConfiguration represents a declarative configuration of the FoundationDBKeyRange type for use
// with apply.
//
// FoundationDBKeyRange describes a range of keys for a command.
//
// The keys in the key range must match the following pattern:
// `^[A-Za-z0-9\/\\-]+$`. All other characters can be escaped with `\xBB`, where
// `BB` is the hexadecimal value of the byte.
type FoundationDBKeyRangeApplyConfiguration struct {
	// Start provides the beginning of the key range.
	Start *string `json:"start,omitempty"`
	// End provides the end of the key range.
	End *string `json:"end,omitempty"`
}

// FoundationDBKeyRangeApplyConfiguration constructs a declarative configuration of the FoundationDBKeyRange type for use with
// apply.
func FoundationDBKeyRange() *FoundationDBKeyRangeApplyConfiguration {
	return &FoundationDBKeyRangeApplyConfiguration{}
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *FoundationDBKeyRangeApplyConfiguration) WithStart(value string) *FoundationDBKeyRangeApplyConfiguration {
	b.Start = &value
	return b
}

// WithEnd sets the End field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the End field is set to the value of the last call.
func (b *FoundationDBKeyRangeApplyConfiguration) WithEnd(value string) *FoundationDBKeyRangeApplyConfiguration {
	b.End = &value
	return b
}
