// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// FoundationDBRestoreStatusApplyConfiguration represents a declarative configuration of the FoundationDBRestoreStatus type for use
// with apply.
//
// FoundationDBRestoreStatus describes the current status of the restore for a cluster.
type FoundationDBRestoreStatusApplyConfiguration struct {
	// Running describes whether the restore is currently running.
	Running *bool `json:"running,omitempty"`
	// State describes the FoundationDBRestoreState state.
	State *apiv1beta2.FoundationDBRestoreState `json:"state,omitempty"`
}

// FoundationDBRestoreStatusApplyConfiguration constructs a declarative configuration of the FoundationDBRestoreStatus type for use with
// apply.
func FoundationDBRestoreStatus() *FoundationDBRestoreStatusApplyConfiguration {
	return &FoundationDBRestoreStatusApplyConfiguration{}
}

// WithRunning sets the Running field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Running field is set to the value of the last call.
func (b *FoundationDBRestoreStatusApplyConfiguration) WithRunning(value bool) *FoundationDBRestoreStatusApplyConfiguration {
	b.Running = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *FoundationDBRestoreStatusApplyConfiguration) WithState(value apiv1beta2.FoundationDBRestoreState) *FoundationDBRestoreStatusApplyConfiguration {
	b.State = &value
	return b
}
