// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
	v1 "k8s.io/api/core/v1"
)

// FoundationDBClusterSpecApplyConfiguration represents a declarative configuration of the FoundationDBClusterSpec type for use
// with apply.
//
// FoundationDBClusterSpec defines the desired state of a cluster.
type FoundationDBClusterSpecApplyConfiguration struct {
	// Version defines the version of FoundationDB the cluster should run.
	Version *string `json:"version,omitempty"`
	// DatabaseConfiguration defines the database configuration.
	DatabaseConfiguration *DatabaseConfigurationApplyConfiguration `json:"databaseConfiguration,omitempty"`
	// Processes defines process-level settings.
	Processes map[apiv1beta2.ProcessClass]ProcessSettingsApplyConfiguration `json:"processes,omitempty"`
	// ProcessCounts defines the number of processes to configure for each
	// process class. You can generally omit this, to allow the operator to
	// infer the process counts based on the database configuration.
	ProcessCounts *ProcessCountsApplyConfiguration `json:"processCounts,omitempty"`
	// SeedConnectionString provides an additional connection string. This connection string will be used in addition
	// to the connection string defined under cluster.Status.ConnectionString to connect to the cluster. This setting
	// can be used to create a multi-region cluster or to recover a cluster if it is out of sync.
	SeedConnectionString *string `json:"seedConnectionString,omitempty"`
	// PartialConnectionString provides a way to specify part of the
	// connection string (e.g. the database name and coordinator generation)
	// without specifying the entire string. This does not allow for setting
	// the coordinator IPs. If `SeedConnectionString` is set,
	// `PartialConnectionString` will have no effect. They cannot be used
	// together.
	PartialConnectionString *ConnectionStringApplyConfiguration `json:"partialConnectionString,omitempty"`
	// FaultDomain defines the rules for what fault domain to replicate across.
	FaultDomain *FoundationDBClusterFaultDomainApplyConfiguration `json:"faultDomain,omitempty"`
	// ProcessGroupsToRemove defines the process groups that we should remove from the
	// cluster. This list contains the process group IDs.
	ProcessGroupsToRemove []apiv1beta2.ProcessGroupID `json:"processGroupsToRemove,omitempty"`
	// ProcessGroupsToRemoveWithoutExclusion defines the process groups that we should
	// remove from the cluster without excluding them. This list contains the
	// process group IDs.
	//
	// This should be used for cases where a pod does not have an IP address and
	// you want to remove it and destroy its volume without confirming the data
	// is fully replicated.
	ProcessGroupsToRemoveWithoutExclusion []apiv1beta2.ProcessGroupID `json:"processGroupsToRemoveWithoutExclusion,omitempty"`
	// ConfigMap allows customizing the config map the operator creates.
	ConfigMap *v1.ConfigMap `json:"configMap,omitempty"`
	// MainContainer defines customization for the foundationdb container.
	MainContainer *ContainerOverridesApplyConfiguration `json:"mainContainer,omitempty"`
	// SidecarContainer defines customization for the
	// foundationdb-kubernetes-sidecar container.
	SidecarContainer *ContainerOverridesApplyConfiguration `json:"sidecarContainer,omitempty"`
	// TrustedCAs defines a list of root CAs the cluster should trust, in PEM
	// format.
	TrustedCAs []string `json:"trustedCAs,omitempty"`
	// SidecarVariables defines Custom variables that the sidecar should make
	// available for substitution in the monitor conf file.
	SidecarVariables []string `json:"sidecarVariables,omitempty"`
	// LogGroup defines the log group to use for the trace logs for the cluster.
	LogGroup *string `json:"logGroup,omitempty"`
	// DataCenter defines the data center where these processes are running.
	DataCenter *string `json:"dataCenter,omitempty"`
	// DataHall defines the data hall where these processes are running.
	DataHall *string `json:"dataHall,omitempty"`
	// AutomationOptions defines customization for enabling or disabling certain
	// operations in the operator.
	AutomationOptions *FoundationDBClusterAutomationOptionsApplyConfiguration `json:"automationOptions,omitempty"`
	// ProcessGroupIDPrefix defines a prefix to append to the process group IDs in the
	// locality fields.
	//
	// This must be a valid Kubernetes label value. See
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
	// for more details on that.
	ProcessGroupIDPrefix *string `json:"processGroupIDPrefix,omitempty"`
	// LockOptions allows customizing how we manage locks for global operations.
	LockOptions *LockOptionsApplyConfiguration `json:"lockOptions,omitempty"`
	// Routing defines the configuration for routing to our pods.
	Routing *RoutingConfigApplyConfiguration `json:"routing,omitempty"`
	// IgnoreUpgradabilityChecks determines whether we should skip the checks for
	// version compatibility when performing an upgrade.
	IgnoreUpgradabilityChecks *bool `json:"ignoreUpgradabilityChecks,omitempty"`
	// Buggify defines settings for injecting faults into a cluster for testing.
	Buggify *BuggifyConfigApplyConfiguration `json:"buggify,omitempty"`
	// StorageServersPerPod defines how many Storage Servers should run in
	// a single process group (Pod). This number defines the number of processes running
	// in one Pod whereas the ProcessCounts defines the number of Pods created.
	// This means that you end up with ProcessCounts["storage"] * StorageServersPerPod
	// storage processes.
	StorageServersPerPod *int `json:"storageServersPerPod,omitempty"`
	// LogServersPerPod defines how many Log Servers should run in
	// a single process group (Pod). This number defines the number of processes running
	// in one Pod whereas the ProcessCounts defines the number of Pods created.
	// This means that you end up with ProcessCounts["Log"] * LogServersPerPod
	// log processes. This also affects processes with the transaction class.
	LogServersPerPod *int `json:"logServersPerPod,omitempty"`
	// MinimumUptimeSecondsForBounce defines the minimum time, in seconds, that the
	// processes in the cluster must have been up for before the operator can
	// execute a bounce.
	MinimumUptimeSecondsForBounce *int `json:"minimumUptimeSecondsForBounce,omitempty"`
	// ReplaceInstancesWhenResourcesChange defines if an instance should be replaced
	// when the resource requirements are increased. This can be useful with the combination of
	// local storage.
	ReplaceInstancesWhenResourcesChange *bool `json:"replaceInstancesWhenResourcesChange,omitempty"`
	// Skip defines if the cluster should be skipped for reconciliation. This can be useful for
	// investigating in issues or if the environment is unstable.
	Skip *bool `json:"skip,omitempty"`
	// CoordinatorSelection defines which process classes are eligible for coordinator selection.
	// If empty all stateful processes classes are equally eligible.
	// A higher priority means that a process class is preferred over another process class.
	// If the FoundationDB cluster is spans across multiple Kubernetes clusters or DCs the
	// CoordinatorSelection must match in all FoundationDB cluster resources otherwise
	// the coordinator selection process could conflict.
	CoordinatorSelection []CoordinatorSelectionSettingApplyConfiguration `json:"coordinatorSelection,omitempty"`
	// LabelConfig allows customizing labels used by the operator.
	LabelConfig *LabelConfigApplyConfiguration `json:"labels,omitempty"`
	// UseExplicitListenAddress determines if we should add a listen address
	// that is separate from the public address.
	// Deprecated: This setting will be removed in the next major release.
	UseExplicitListenAddress *bool `json:"useExplicitListenAddress,omitempty"`
	// ImageType defines the image type that should be used for the FoundationDBCluster deployment. When the type
	// is set to "unified" the deployment will use the new fdb-kubernetes-monitor. Otherwise the main container and
	// the sidecar container will use different images.
	// Default: split
	ImageType *apiv1beta2.ImageType `json:"imageType,omitempty"`
	// MaxZonesWithUnavailablePods defines the maximum number of zones that can have unavailable pods during the update process.
	// When unset, there is no limit to the  number of zones with unavailable pods.
	MaxZonesWithUnavailablePods *int `json:"maxZonesWithUnavailablePods,omitempty"`
}

// FoundationDBClusterSpecApplyConfiguration constructs a declarative configuration of the FoundationDBClusterSpec type for use with
// apply.
func FoundationDBClusterSpec() *FoundationDBClusterSpecApplyConfiguration {
	return &FoundationDBClusterSpecApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithVersion(value string) *FoundationDBClusterSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithDatabaseConfiguration sets the DatabaseConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DatabaseConfiguration field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithDatabaseConfiguration(value *DatabaseConfigurationApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.DatabaseConfiguration = value
	return b
}

// WithProcesses puts the entries into the Processes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Processes field,
// overwriting an existing map entries in Processes field with the same key.
func (b *FoundationDBClusterSpecApplyConfiguration) WithProcesses(entries map[apiv1beta2.ProcessClass]ProcessSettingsApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	if b.Processes == nil && len(entries) > 0 {
		b.Processes = make(map[apiv1beta2.ProcessClass]ProcessSettingsApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Processes[k] = v
	}
	return b
}

// WithProcessCounts sets the ProcessCounts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessCounts field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithProcessCounts(value *ProcessCountsApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.ProcessCounts = value
	return b
}

// WithSeedConnectionString sets the SeedConnectionString field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeedConnectionString field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithSeedConnectionString(value string) *FoundationDBClusterSpecApplyConfiguration {
	b.SeedConnectionString = &value
	return b
}

// WithPartialConnectionString sets the PartialConnectionString field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartialConnectionString field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithPartialConnectionString(value *ConnectionStringApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.PartialConnectionString = value
	return b
}

// WithFaultDomain sets the FaultDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FaultDomain field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithFaultDomain(value *FoundationDBClusterFaultDomainApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.FaultDomain = value
	return b
}

// WithProcessGroupsToRemove adds the given value to the ProcessGroupsToRemove field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessGroupsToRemove field.
func (b *FoundationDBClusterSpecApplyConfiguration) WithProcessGroupsToRemove(values ...apiv1beta2.ProcessGroupID) *FoundationDBClusterSpecApplyConfiguration {
	for i := range values {
		b.ProcessGroupsToRemove = append(b.ProcessGroupsToRemove, values[i])
	}
	return b
}

// WithProcessGroupsToRemoveWithoutExclusion adds the given value to the ProcessGroupsToRemoveWithoutExclusion field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessGroupsToRemoveWithoutExclusion field.
func (b *FoundationDBClusterSpecApplyConfiguration) WithProcessGroupsToRemoveWithoutExclusion(values ...apiv1beta2.ProcessGroupID) *FoundationDBClusterSpecApplyConfiguration {
	for i := range values {
		b.ProcessGroupsToRemoveWithoutExclusion = append(b.ProcessGroupsToRemoveWithoutExclusion, values[i])
	}
	return b
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithConfigMap(value v1.ConfigMap) *FoundationDBClusterSpecApplyConfiguration {
	b.ConfigMap = &value
	return b
}

// WithMainContainer sets the MainContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainContainer field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithMainContainer(value *ContainerOverridesApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.MainContainer = value
	return b
}

// WithSidecarContainer sets the SidecarContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarContainer field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithSidecarContainer(value *ContainerOverridesApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.SidecarContainer = value
	return b
}

// WithTrustedCAs adds the given value to the TrustedCAs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TrustedCAs field.
func (b *FoundationDBClusterSpecApplyConfiguration) WithTrustedCAs(values ...string) *FoundationDBClusterSpecApplyConfiguration {
	for i := range values {
		b.TrustedCAs = append(b.TrustedCAs, values[i])
	}
	return b
}

// WithSidecarVariables adds the given value to the SidecarVariables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SidecarVariables field.
func (b *FoundationDBClusterSpecApplyConfiguration) WithSidecarVariables(values ...string) *FoundationDBClusterSpecApplyConfiguration {
	for i := range values {
		b.SidecarVariables = append(b.SidecarVariables, values[i])
	}
	return b
}

// WithLogGroup sets the LogGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogGroup field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithLogGroup(value string) *FoundationDBClusterSpecApplyConfiguration {
	b.LogGroup = &value
	return b
}

// WithDataCenter sets the DataCenter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataCenter field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithDataCenter(value string) *FoundationDBClusterSpecApplyConfiguration {
	b.DataCenter = &value
	return b
}

// WithDataHall sets the DataHall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataHall field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithDataHall(value string) *FoundationDBClusterSpecApplyConfiguration {
	b.DataHall = &value
	return b
}

// WithAutomationOptions sets the AutomationOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutomationOptions field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithAutomationOptions(value *FoundationDBClusterAutomationOptionsApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.AutomationOptions = value
	return b
}

// WithProcessGroupIDPrefix sets the ProcessGroupIDPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessGroupIDPrefix field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithProcessGroupIDPrefix(value string) *FoundationDBClusterSpecApplyConfiguration {
	b.ProcessGroupIDPrefix = &value
	return b
}

// WithLockOptions sets the LockOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LockOptions field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithLockOptions(value *LockOptionsApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.LockOptions = value
	return b
}

// WithRouting sets the Routing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Routing field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithRouting(value *RoutingConfigApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.Routing = value
	return b
}

// WithIgnoreUpgradabilityChecks sets the IgnoreUpgradabilityChecks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreUpgradabilityChecks field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithIgnoreUpgradabilityChecks(value bool) *FoundationDBClusterSpecApplyConfiguration {
	b.IgnoreUpgradabilityChecks = &value
	return b
}

// WithBuggify sets the Buggify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Buggify field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithBuggify(value *BuggifyConfigApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.Buggify = value
	return b
}

// WithStorageServersPerPod sets the StorageServersPerPod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageServersPerPod field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithStorageServersPerPod(value int) *FoundationDBClusterSpecApplyConfiguration {
	b.StorageServersPerPod = &value
	return b
}

// WithLogServersPerPod sets the LogServersPerPod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogServersPerPod field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithLogServersPerPod(value int) *FoundationDBClusterSpecApplyConfiguration {
	b.LogServersPerPod = &value
	return b
}

// WithMinimumUptimeSecondsForBounce sets the MinimumUptimeSecondsForBounce field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumUptimeSecondsForBounce field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithMinimumUptimeSecondsForBounce(value int) *FoundationDBClusterSpecApplyConfiguration {
	b.MinimumUptimeSecondsForBounce = &value
	return b
}

// WithReplaceInstancesWhenResourcesChange sets the ReplaceInstancesWhenResourcesChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplaceInstancesWhenResourcesChange field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithReplaceInstancesWhenResourcesChange(value bool) *FoundationDBClusterSpecApplyConfiguration {
	b.ReplaceInstancesWhenResourcesChange = &value
	return b
}

// WithSkip sets the Skip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Skip field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithSkip(value bool) *FoundationDBClusterSpecApplyConfiguration {
	b.Skip = &value
	return b
}

// WithCoordinatorSelection adds the given value to the CoordinatorSelection field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CoordinatorSelection field.
func (b *FoundationDBClusterSpecApplyConfiguration) WithCoordinatorSelection(values ...*CoordinatorSelectionSettingApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCoordinatorSelection")
		}
		b.CoordinatorSelection = append(b.CoordinatorSelection, *values[i])
	}
	return b
}

// WithLabelConfig sets the LabelConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelConfig field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithLabelConfig(value *LabelConfigApplyConfiguration) *FoundationDBClusterSpecApplyConfiguration {
	b.LabelConfig = value
	return b
}

// WithUseExplicitListenAddress sets the UseExplicitListenAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseExplicitListenAddress field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithUseExplicitListenAddress(value bool) *FoundationDBClusterSpecApplyConfiguration {
	b.UseExplicitListenAddress = &value
	return b
}

// WithImageType sets the ImageType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageType field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithImageType(value apiv1beta2.ImageType) *FoundationDBClusterSpecApplyConfiguration {
	b.ImageType = &value
	return b
}

// WithMaxZonesWithUnavailablePods sets the MaxZonesWithUnavailablePods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxZonesWithUnavailablePods field is set to the value of the last call.
func (b *FoundationDBClusterSpecApplyConfiguration) WithMaxZonesWithUnavailablePods(value int) *FoundationDBClusterSpecApplyConfiguration {
	b.MaxZonesWithUnavailablePods = &value
	return b
}
