// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// FoundationDBClusterStatusApplyConfiguration represents a declarative configuration of the FoundationDBClusterStatus type for use
// with apply.
//
// FoundationDBClusterStatus defines the observed state of FoundationDBCluster
type FoundationDBClusterStatusApplyConfiguration struct {
	// DatabaseConfiguration provides the running configuration of the database.
	DatabaseConfiguration *DatabaseConfigurationApplyConfiguration `json:"databaseConfiguration,omitempty"`
	// Generations provides information about the latest generation to be
	// reconciled, or to reach other stages at which reconciliation can halt.
	Generations *ClusterGenerationStatusApplyConfiguration `json:"generations,omitempty"`
	// Health provides information about the health of the database.
	Health *ClusterHealthApplyConfiguration `json:"health,omitempty"`
	// RequiredAddresses define that addresses that we need to enable for the
	// processes in the cluster.
	RequiredAddresses *RequiredAddressSetApplyConfiguration `json:"requiredAddresses,omitempty"`
	// HasIncorrectConfigMap indicates whether the latest config map is out
	// of date with the cluster spec.
	HasIncorrectConfigMap *bool `json:"hasIncorrectConfigMap,omitempty"`
	// HasIncorrectServiceConfig indicates whether the cluster has service
	// config that is out of date with the cluster spec.
	HasIncorrectServiceConfig *bool `json:"hasIncorrectServiceConfig,omitempty"`
	// NeedsNewCoordinators indicates whether the cluster needs to recruit
	// new coordinators to fulfill its fault tolerance requirements.
	NeedsNewCoordinators *bool `json:"needsNewCoordinators,omitempty"`
	// RunningVersion defines the version of FoundationDB that the cluster is
	// currently running.
	RunningVersion *string `json:"runningVersion,omitempty"`
	// ConnectionString defines the contents of the cluster file.
	ConnectionString *string `json:"connectionString,omitempty"`
	// Configured defines whether we have configured the database yet.
	Configured *bool `json:"configured,omitempty"`
	// HasListenIPsForAllPods defines whether every pod has an environment
	// variable for its listen address.
	HasListenIPsForAllPods *bool `json:"hasListenIPsForAllPods,omitempty"`
	// StorageServersPerDisk defines the storageServersPerPod observed in the cluster.
	// If there are more than one value in the slice the reconcile phase is not finished.
	StorageServersPerDisk []int `json:"storageServersPerDisk,omitempty"`
	// LogServersPerDisk defines the LogServersPerDisk observed in the cluster.
	// If there are more than one value in the slice the reconcile phase is not finished.
	LogServersPerDisk []int `json:"logServersPerDisk,omitempty"`
	// ImageTypes defines the kinds of images that are in use in the cluster.
	// If there is more than one value in the slice the reconcile phase is not
	// finished.
	ImageTypes []apiv1beta2.ImageType `json:"imageTypes,omitempty"`
	// ProcessGroups contain information about a process group.
	// This information is used in multiple places to trigger the according action.
	ProcessGroups []*apiv1beta2.ProcessGroupStatus `json:"processGroups,omitempty"`
	// Locks contains information about the locking system.
	Locks *LockSystemStatusApplyConfiguration `json:"locks,omitempty"`
	// MaintenenanceModeInfo contains information regarding process groups in maintenance mode
	// Deprecated: This setting is not used anymore.
	MaintenanceModeInfo *MaintenanceModeInfoApplyConfiguration `json:"maintenanceModeInfo,omitempty"`
	// DesiredProcessGroups reflects the number of expected running process groups.
	DesiredProcessGroups *int `json:"desiredProcessGroups,omitempty"`
	// ReconciledProcessGroups reflects the number of process groups that have no condition and are not marked for removal.
	ReconciledProcessGroups *int `json:"reconciledProcessGroups,omitempty"`
}

// FoundationDBClusterStatusApplyConfiguration constructs a declarative configuration of the FoundationDBClusterStatus type for use with
// apply.
func FoundationDBClusterStatus() *FoundationDBClusterStatusApplyConfiguration {
	return &FoundationDBClusterStatusApplyConfiguration{}
}

// WithDatabaseConfiguration sets the DatabaseConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DatabaseConfiguration field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithDatabaseConfiguration(value *DatabaseConfigurationApplyConfiguration) *FoundationDBClusterStatusApplyConfiguration {
	b.DatabaseConfiguration = value
	return b
}

// WithGenerations sets the Generations field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generations field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithGenerations(value *ClusterGenerationStatusApplyConfiguration) *FoundationDBClusterStatusApplyConfiguration {
	b.Generations = value
	return b
}

// WithHealth sets the Health field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Health field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithHealth(value *ClusterHealthApplyConfiguration) *FoundationDBClusterStatusApplyConfiguration {
	b.Health = value
	return b
}

// WithRequiredAddresses sets the RequiredAddresses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredAddresses field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithRequiredAddresses(value *RequiredAddressSetApplyConfiguration) *FoundationDBClusterStatusApplyConfiguration {
	b.RequiredAddresses = value
	return b
}

// WithHasIncorrectConfigMap sets the HasIncorrectConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasIncorrectConfigMap field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithHasIncorrectConfigMap(value bool) *FoundationDBClusterStatusApplyConfiguration {
	b.HasIncorrectConfigMap = &value
	return b
}

// WithHasIncorrectServiceConfig sets the HasIncorrectServiceConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasIncorrectServiceConfig field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithHasIncorrectServiceConfig(value bool) *FoundationDBClusterStatusApplyConfiguration {
	b.HasIncorrectServiceConfig = &value
	return b
}

// WithNeedsNewCoordinators sets the NeedsNewCoordinators field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeedsNewCoordinators field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithNeedsNewCoordinators(value bool) *FoundationDBClusterStatusApplyConfiguration {
	b.NeedsNewCoordinators = &value
	return b
}

// WithRunningVersion sets the RunningVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunningVersion field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithRunningVersion(value string) *FoundationDBClusterStatusApplyConfiguration {
	b.RunningVersion = &value
	return b
}

// WithConnectionString sets the ConnectionString field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionString field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithConnectionString(value string) *FoundationDBClusterStatusApplyConfiguration {
	b.ConnectionString = &value
	return b
}

// WithConfigured sets the Configured field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Configured field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithConfigured(value bool) *FoundationDBClusterStatusApplyConfiguration {
	b.Configured = &value
	return b
}

// WithHasListenIPsForAllPods sets the HasListenIPsForAllPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasListenIPsForAllPods field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithHasListenIPsForAllPods(value bool) *FoundationDBClusterStatusApplyConfiguration {
	b.HasListenIPsForAllPods = &value
	return b
}

// WithStorageServersPerDisk adds the given value to the StorageServersPerDisk field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the StorageServersPerDisk field.
func (b *FoundationDBClusterStatusApplyConfiguration) WithStorageServersPerDisk(values ...int) *FoundationDBClusterStatusApplyConfiguration {
	for i := range values {
		b.StorageServersPerDisk = append(b.StorageServersPerDisk, values[i])
	}
	return b
}

// WithLogServersPerDisk adds the given value to the LogServersPerDisk field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LogServersPerDisk field.
func (b *FoundationDBClusterStatusApplyConfiguration) WithLogServersPerDisk(values ...int) *FoundationDBClusterStatusApplyConfiguration {
	for i := range values {
		b.LogServersPerDisk = append(b.LogServersPerDisk, values[i])
	}
	return b
}

// WithImageTypes adds the given value to the ImageTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImageTypes field.
func (b *FoundationDBClusterStatusApplyConfiguration) WithImageTypes(values ...apiv1beta2.ImageType) *FoundationDBClusterStatusApplyConfiguration {
	for i := range values {
		b.ImageTypes = append(b.ImageTypes, values[i])
	}
	return b
}

// WithProcessGroups adds the given value to the ProcessGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessGroups field.
func (b *FoundationDBClusterStatusApplyConfiguration) WithProcessGroups(values ...**apiv1beta2.ProcessGroupStatus) *FoundationDBClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProcessGroups")
		}
		b.ProcessGroups = append(b.ProcessGroups, *values[i])
	}
	return b
}

// WithLocks sets the Locks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Locks field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithLocks(value *LockSystemStatusApplyConfiguration) *FoundationDBClusterStatusApplyConfiguration {
	b.Locks = value
	return b
}

// WithMaintenanceModeInfo sets the MaintenanceModeInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceModeInfo field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithMaintenanceModeInfo(value *MaintenanceModeInfoApplyConfiguration) *FoundationDBClusterStatusApplyConfiguration {
	b.MaintenanceModeInfo = value
	return b
}

// WithDesiredProcessGroups sets the DesiredProcessGroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredProcessGroups field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithDesiredProcessGroups(value int) *FoundationDBClusterStatusApplyConfiguration {
	b.DesiredProcessGroups = &value
	return b
}

// WithReconciledProcessGroups sets the ReconciledProcessGroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReconciledProcessGroups field is set to the value of the last call.
func (b *FoundationDBClusterStatusApplyConfiguration) WithReconciledProcessGroups(value int) *FoundationDBClusterStatusApplyConfiguration {
	b.ReconciledProcessGroups = &value
	return b
}
