// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// FoundationDBBackupStatusApplyConfiguration represents a declarative configuration of the FoundationDBBackupStatus type for use
// with apply.
//
// FoundationDBBackupStatus describes the current status of the backup for a cluster.
type FoundationDBBackupStatusApplyConfiguration struct {
	// AgentCount provides the number of agents that are up-to-date, ready,
	// and not terminated.
	AgentCount *int `json:"agentCount,omitempty"`
	// DeploymentConfigured indicates whether the deployment is correctly
	// configured.
	DeploymentConfigured *bool `json:"deploymentConfigured,omitempty"`
	// BackupDetails provides information about the state of the backup in the
	// cluster.
	BackupDetails *FoundationDBBackupStatusBackupDetailsApplyConfiguration `json:"backupDetails,omitempty"`
	// Generations provides information about the latest generation to be
	// reconciled, or to reach other stages in reconciliation.
	Generations *BackupGenerationStatusApplyConfiguration `json:"generations,omitempty"`
}

// FoundationDBBackupStatusApplyConfiguration constructs a declarative configuration of the FoundationDBBackupStatus type for use with
// apply.
func FoundationDBBackupStatus() *FoundationDBBackupStatusApplyConfiguration {
	return &FoundationDBBackupStatusApplyConfiguration{}
}

// WithAgentCount sets the AgentCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentCount field is set to the value of the last call.
func (b *FoundationDBBackupStatusApplyConfiguration) WithAgentCount(value int) *FoundationDBBackupStatusApplyConfiguration {
	b.AgentCount = &value
	return b
}

// WithDeploymentConfigured sets the DeploymentConfigured field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentConfigured field is set to the value of the last call.
func (b *FoundationDBBackupStatusApplyConfiguration) WithDeploymentConfigured(value bool) *FoundationDBBackupStatusApplyConfiguration {
	b.DeploymentConfigured = &value
	return b
}

// WithBackupDetails sets the BackupDetails field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupDetails field is set to the value of the last call.
func (b *FoundationDBBackupStatusApplyConfiguration) WithBackupDetails(value *FoundationDBBackupStatusBackupDetailsApplyConfiguration) *FoundationDBBackupStatusApplyConfiguration {
	b.BackupDetails = value
	return b
}

// WithGenerations sets the Generations field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generations field is set to the value of the last call.
func (b *FoundationDBBackupStatusApplyConfiguration) WithGenerations(value *BackupGenerationStatusApplyConfiguration) *FoundationDBBackupStatusApplyConfiguration {
	b.Generations = value
	return b
}
