// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// ImageConfigApplyConfiguration represents a declarative configuration of the ImageConfig type for use
// with apply.
//
// ImageConfig provides a policy for customizing an image.
//
// When multiple image configs are provided, they will be merged into a single
// config that will be used to define the final image. For each field, we select
// the value from the first entry in the config list that defines a value for
// that field, and matches the version of FoundationDB the image is for. Any
// config that specifies a different version than the one under consideration
// will be ignored for the purposes of defining that image.
type ImageConfigApplyConfiguration struct {
	// Version is the version of FoundationDB this policy applies to. If this is
	// blank, the policy applies to all FDB versions.
	Version *string `json:"version,omitempty"`
	// BaseImage specifies the part of the image before the tag.
	BaseImage *string `json:"baseImage,omitempty"`
	// Tag specifies a full image tag.
	Tag *string `json:"tag,omitempty"`
	// TagSuffix specifies a suffix that will be added after the version to form
	// the full tag.
	TagSuffix *string `json:"tagSuffix,omitempty"`
}

// ImageConfigApplyConfiguration constructs a declarative configuration of the ImageConfig type for use with
// apply.
func ImageConfig() *ImageConfigApplyConfiguration {
	return &ImageConfigApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ImageConfigApplyConfiguration) WithVersion(value string) *ImageConfigApplyConfiguration {
	b.Version = &value
	return b
}

// WithBaseImage sets the BaseImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseImage field is set to the value of the last call.
func (b *ImageConfigApplyConfiguration) WithBaseImage(value string) *ImageConfigApplyConfiguration {
	b.BaseImage = &value
	return b
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *ImageConfigApplyConfiguration) WithTag(value string) *ImageConfigApplyConfiguration {
	b.Tag = &value
	return b
}

// WithTagSuffix sets the TagSuffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TagSuffix field is set to the value of the last call.
func (b *ImageConfigApplyConfiguration) WithTagSuffix(value string) *ImageConfigApplyConfiguration {
	b.TagSuffix = &value
	return b
}
