// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// LabelConfigApplyConfiguration represents a declarative configuration of the LabelConfig type for use
// with apply.
//
// LabelConfig allows customizing labels used by the operator.
type LabelConfigApplyConfiguration struct {
	// MatchLabels provides the labels that the operator should use to identify
	// resources owned by the cluster. These will automatically be applied to
	// all resources the operator creates.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
	// ResourceLabels provides additional labels that the operator should apply to
	// resources it creates.
	ResourceLabels map[string]string `json:"resourceLabels,omitempty"`
	// ProcessGroupIDLabels provides the labels that we use for the process group ID
	// field. The first label will be used by the operator when filtering
	// resources.
	ProcessGroupIDLabels []string `json:"processGroupIDLabels,omitempty"`
	// ProcessClassLabels provides the labels that we use for the process class
	// field. The first label will be used by the operator when filtering
	// resources.
	ProcessClassLabels []string `json:"processClassLabels,omitempty"`
	// FilterOnOwnerReferences determines whether we should check that resources
	// are owned by the cluster object, in addition to the constraints provided
	// by the match labels.
	// Deprecated: This setting will be removed in the next major release.
	FilterOnOwnerReferences *bool `json:"filterOnOwnerReference,omitempty"`
}

// LabelConfigApplyConfiguration constructs a declarative configuration of the LabelConfig type for use with
// apply.
func LabelConfig() *LabelConfigApplyConfiguration {
	return &LabelConfigApplyConfiguration{}
}

// WithMatchLabels puts the entries into the MatchLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MatchLabels field,
// overwriting an existing map entries in MatchLabels field with the same key.
func (b *LabelConfigApplyConfiguration) WithMatchLabels(entries map[string]string) *LabelConfigApplyConfiguration {
	if b.MatchLabels == nil && len(entries) > 0 {
		b.MatchLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.MatchLabels[k] = v
	}
	return b
}

// WithResourceLabels puts the entries into the ResourceLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ResourceLabels field,
// overwriting an existing map entries in ResourceLabels field with the same key.
func (b *LabelConfigApplyConfiguration) WithResourceLabels(entries map[string]string) *LabelConfigApplyConfiguration {
	if b.ResourceLabels == nil && len(entries) > 0 {
		b.ResourceLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ResourceLabels[k] = v
	}
	return b
}

// WithProcessGroupIDLabels adds the given value to the ProcessGroupIDLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessGroupIDLabels field.
func (b *LabelConfigApplyConfiguration) WithProcessGroupIDLabels(values ...string) *LabelConfigApplyConfiguration {
	for i := range values {
		b.ProcessGroupIDLabels = append(b.ProcessGroupIDLabels, values[i])
	}
	return b
}

// WithProcessClassLabels adds the given value to the ProcessClassLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessClassLabels field.
func (b *LabelConfigApplyConfiguration) WithProcessClassLabels(values ...string) *LabelConfigApplyConfiguration {
	for i := range values {
		b.ProcessClassLabels = append(b.ProcessClassLabels, values[i])
	}
	return b
}

// WithFilterOnOwnerReferences sets the FilterOnOwnerReferences field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FilterOnOwnerReferences field is set to the value of the last call.
func (b *LabelConfigApplyConfiguration) WithFilterOnOwnerReferences(value bool) *LabelConfigApplyConfiguration {
	b.FilterOnOwnerReferences = &value
	return b
}
