// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// LockSystemStatusApplyConfiguration represents a declarative configuration of the LockSystemStatus type for use
// with apply.
//
// LockSystemStatus provides a summary of the status of the locking system.
type LockSystemStatusApplyConfiguration struct {
	// DenyList contains a list of operator instances that are prevented
	// from taking locks.
	DenyList []string `json:"lockDenyList,omitempty"`
}

// LockSystemStatusApplyConfiguration constructs a declarative configuration of the LockSystemStatus type for use with
// apply.
func LockSystemStatus() *LockSystemStatusApplyConfiguration {
	return &LockSystemStatusApplyConfiguration{}
}

// WithDenyList adds the given value to the DenyList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DenyList field.
func (b *LockSystemStatusApplyConfiguration) WithDenyList(values ...string) *LockSystemStatusApplyConfiguration {
	for i := range values {
		b.DenyList = append(b.DenyList, values[i])
	}
	return b
}
