// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// LockDenyListEntryApplyConfiguration represents a declarative configuration of the LockDenyListEntry type for use
// with apply.
//
// LockDenyListEntry models an entry in the deny list for the locking system.
type LockDenyListEntryApplyConfiguration struct {
	// The ID of the operator instance this entry is targeting.
	ID *string `json:"id,omitempty"`
	// Whether the instance is allowed to take locks.
	Allow *bool `json:"allow,omitempty"`
}

// LockDenyListEntryApplyConfiguration constructs a declarative configuration of the LockDenyListEntry type for use with
// apply.
func LockDenyListEntry() *LockDenyListEntryApplyConfiguration {
	return &LockDenyListEntryApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *LockDenyListEntryApplyConfiguration) WithID(value string) *LockDenyListEntryApplyConfiguration {
	b.ID = &value
	return b
}

// WithAllow sets the Allow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allow field is set to the value of the last call.
func (b *LockDenyListEntryApplyConfiguration) WithAllow(value bool) *LockDenyListEntryApplyConfiguration {
	b.Allow = &value
	return b
}
