// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// LockOptionsApplyConfiguration represents a declarative configuration of the LockOptions type for use
// with apply.
//
// LockOptions provides customization for locking global operations.
type LockOptionsApplyConfiguration struct {
	// DisableLocks determines whether we should disable locking entirely.
	DisableLocks *bool `json:"disableLocks,omitempty"`
	// LockKeyPrefix provides a custom prefix for the keys in the database we
	// use to store locks.
	LockKeyPrefix *string `json:"lockKeyPrefix,omitempty"`
	// LockDurationMinutes determines the duration that locks should be valid
	// for.
	LockDurationMinutes *int `json:"lockDurationMinutes,omitempty"`
	// DenyList manages configuration for whether an instance of the operator
	// should be denied from taking locks.
	DenyList []LockDenyListEntryApplyConfiguration `json:"denyList,omitempty"`
}

// LockOptionsApplyConfiguration constructs a declarative configuration of the LockOptions type for use with
// apply.
func LockOptions() *LockOptionsApplyConfiguration {
	return &LockOptionsApplyConfiguration{}
}

// WithDisableLocks sets the DisableLocks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableLocks field is set to the value of the last call.
func (b *LockOptionsApplyConfiguration) WithDisableLocks(value bool) *LockOptionsApplyConfiguration {
	b.DisableLocks = &value
	return b
}

// WithLockKeyPrefix sets the LockKeyPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LockKeyPrefix field is set to the value of the last call.
func (b *LockOptionsApplyConfiguration) WithLockKeyPrefix(value string) *LockOptionsApplyConfiguration {
	b.LockKeyPrefix = &value
	return b
}

// WithLockDurationMinutes sets the LockDurationMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LockDurationMinutes field is set to the value of the last call.
func (b *LockOptionsApplyConfiguration) WithLockDurationMinutes(value int) *LockOptionsApplyConfiguration {
	b.LockDurationMinutes = &value
	return b
}

// WithDenyList adds the given value to the DenyList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DenyList field.
func (b *LockOptionsApplyConfiguration) WithDenyList(values ...*LockDenyListEntryApplyConfiguration) *LockOptionsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDenyList")
		}
		b.DenyList = append(b.DenyList, *values[i])
	}
	return b
}
