// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// MaintenanceModeOptionsApplyConfiguration represents a declarative configuration of the MaintenanceModeOptions type for use
// with apply.
//
// MaintenanceModeOptions controls options for placing zones in maintenance mode.
type MaintenanceModeOptionsApplyConfiguration struct {
	// UseMaintenanceModeChecker defines whether the operator is allowed to use maintenance mode before updating pods.
	// If this setting is set to true the operator will set and reset the maintenance mode when updating pods. If this
	// setting is set to true, then ResetMaintenanceMode will also be enabled to make sure the operator is able to
	// reset the maintenance mode again.
	// Default is false.
	UseMaintenanceModeChecker *bool `json:"UseMaintenanceModeChecker,omitempty"`
	// ResetMaintenanceMode defines whether the operator should reset the maintenance mode if all storage processes
	// under the maintenance zone have been restarted. The default is false. For more details see:
	// https://github.com/FoundationDB/fdb-kubernetes-operator/v2/blob/improve-maintenance-mode-integration/docs/manual/operations.md#maintenance
	// Default is false.
	ResetMaintenanceMode *bool `json:"resetMaintenanceMode,omitempty"`
	// MaintenanceModeTimeSeconds provides the duration for the zone to be in maintenance. It will automatically be switched off after the time elapses.
	// Default is 600.
	MaintenanceModeTimeSeconds *int `json:"maintenanceModeTimeSeconds,omitempty"`
}

// MaintenanceModeOptionsApplyConfiguration constructs a declarative configuration of the MaintenanceModeOptions type for use with
// apply.
func MaintenanceModeOptions() *MaintenanceModeOptionsApplyConfiguration {
	return &MaintenanceModeOptionsApplyConfiguration{}
}

// WithUseMaintenanceModeChecker sets the UseMaintenanceModeChecker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseMaintenanceModeChecker field is set to the value of the last call.
func (b *MaintenanceModeOptionsApplyConfiguration) WithUseMaintenanceModeChecker(value bool) *MaintenanceModeOptionsApplyConfiguration {
	b.UseMaintenanceModeChecker = &value
	return b
}

// WithResetMaintenanceMode sets the ResetMaintenanceMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResetMaintenanceMode field is set to the value of the last call.
func (b *MaintenanceModeOptionsApplyConfiguration) WithResetMaintenanceMode(value bool) *MaintenanceModeOptionsApplyConfiguration {
	b.ResetMaintenanceMode = &value
	return b
}

// WithMaintenanceModeTimeSeconds sets the MaintenanceModeTimeSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceModeTimeSeconds field is set to the value of the last call.
func (b *MaintenanceModeOptionsApplyConfiguration) WithMaintenanceModeTimeSeconds(value int) *MaintenanceModeOptionsApplyConfiguration {
	b.MaintenanceModeTimeSeconds = &value
	return b
}
