// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MaintenanceModeInfoApplyConfiguration represents a declarative configuration of the MaintenanceModeInfo type for use
// with apply.
//
// MaintenanceModeInfo contains information regarding the zone and process groups that are put
// into maintenance mode by the operator
type MaintenanceModeInfoApplyConfiguration struct {
	// StartTimestamp provides the timestamp when this zone is put into maintenance mode
	// Deprecated: This setting is not used anymore.
	StartTimestamp *v1.Time `json:"startTimestamp,omitempty"`
	// ZoneID that is placed in maintenance mode
	// Deprecated: This setting is not used anymore.
	ZoneID *apiv1beta2.FaultDomain `json:"zoneID,omitempty"`
	// ProcessGroups that are placed in maintenance mode
	// Deprecated: This setting is not used anymore.
	ProcessGroups []string `json:"processGroups,omitempty"`
}

// MaintenanceModeInfoApplyConfiguration constructs a declarative configuration of the MaintenanceModeInfo type for use with
// apply.
func MaintenanceModeInfo() *MaintenanceModeInfoApplyConfiguration {
	return &MaintenanceModeInfoApplyConfiguration{}
}

// WithStartTimestamp sets the StartTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTimestamp field is set to the value of the last call.
func (b *MaintenanceModeInfoApplyConfiguration) WithStartTimestamp(value v1.Time) *MaintenanceModeInfoApplyConfiguration {
	b.StartTimestamp = &value
	return b
}

// WithZoneID sets the ZoneID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneID field is set to the value of the last call.
func (b *MaintenanceModeInfoApplyConfiguration) WithZoneID(value apiv1beta2.FaultDomain) *MaintenanceModeInfoApplyConfiguration {
	b.ZoneID = &value
	return b
}

// WithProcessGroups adds the given value to the ProcessGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessGroups field.
func (b *MaintenanceModeInfoApplyConfiguration) WithProcessGroups(values ...string) *MaintenanceModeInfoApplyConfiguration {
	for i := range values {
		b.ProcessGroups = append(b.ProcessGroups, values[i])
	}
	return b
}
