// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// ProcessCountsApplyConfiguration represents a declarative configuration of the ProcessCounts type for use
// with apply.
//
// ProcessCounts represents the number of processes we have for each valid
// process class.
//
// If one of the counts in the spec is set to 0, we will infer the process count
// for that class from the role counts. If one of the counts in the spec is set
// to -1, we will not create any processes for that class. See
// GetProcessCountsWithDefaults for more information on the rules for inferring
// process counts.
type ProcessCountsApplyConfiguration struct {
	Unset       *int `json:"unset,omitempty"`
	Storage     *int `json:"storage,omitempty"`
	Transaction *int `json:"transaction,omitempty"`
	Resolution  *int `json:"resolution,omitempty"`
	// Deprecated: This setting will be removed in the next major release.
	// use Test
	Tester            *int `json:"tester,omitempty"`
	Test              *int `json:"test,omitempty"`
	Proxy             *int `json:"proxy,omitempty"`
	CommitProxy       *int `json:"commit_proxy,omitempty"`
	GrvProxy          *int `json:"grv_proxy,omitempty"`
	Master            *int `json:"master,omitempty"`
	Stateless         *int `json:"stateless,omitempty"`
	Log               *int `json:"log,omitempty"`
	ClusterController *int `json:"cluster_controller,omitempty"`
	LogRouter         *int `json:"router,omitempty"`
	FastRestore       *int `json:"fast_restore,omitempty"`
	DataDistributor   *int `json:"data_distributor,omitempty"`
	Coordinator       *int `json:"coordinator,omitempty"`
	Ratekeeper        *int `json:"ratekeeper,omitempty"`
	StorageCache      *int `json:"storage_cache,omitempty"`
	BackupWorker      *int `json:"backup,omitempty"`
}

// ProcessCountsApplyConfiguration constructs a declarative configuration of the ProcessCounts type for use with
// apply.
func ProcessCounts() *ProcessCountsApplyConfiguration {
	return &ProcessCountsApplyConfiguration{}
}

// WithUnset sets the Unset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unset field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithUnset(value int) *ProcessCountsApplyConfiguration {
	b.Unset = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithStorage(value int) *ProcessCountsApplyConfiguration {
	b.Storage = &value
	return b
}

// WithTransaction sets the Transaction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transaction field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithTransaction(value int) *ProcessCountsApplyConfiguration {
	b.Transaction = &value
	return b
}

// WithResolution sets the Resolution field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resolution field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithResolution(value int) *ProcessCountsApplyConfiguration {
	b.Resolution = &value
	return b
}

// WithTester sets the Tester field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tester field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithTester(value int) *ProcessCountsApplyConfiguration {
	b.Tester = &value
	return b
}

// WithTest sets the Test field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Test field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithTest(value int) *ProcessCountsApplyConfiguration {
	b.Test = &value
	return b
}

// WithProxy sets the Proxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Proxy field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithProxy(value int) *ProcessCountsApplyConfiguration {
	b.Proxy = &value
	return b
}

// WithCommitProxy sets the CommitProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitProxy field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithCommitProxy(value int) *ProcessCountsApplyConfiguration {
	b.CommitProxy = &value
	return b
}

// WithGrvProxy sets the GrvProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrvProxy field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithGrvProxy(value int) *ProcessCountsApplyConfiguration {
	b.GrvProxy = &value
	return b
}

// WithMaster sets the Master field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Master field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithMaster(value int) *ProcessCountsApplyConfiguration {
	b.Master = &value
	return b
}

// WithStateless sets the Stateless field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stateless field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithStateless(value int) *ProcessCountsApplyConfiguration {
	b.Stateless = &value
	return b
}

// WithLog sets the Log field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Log field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithLog(value int) *ProcessCountsApplyConfiguration {
	b.Log = &value
	return b
}

// WithClusterController sets the ClusterController field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterController field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithClusterController(value int) *ProcessCountsApplyConfiguration {
	b.ClusterController = &value
	return b
}

// WithLogRouter sets the LogRouter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogRouter field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithLogRouter(value int) *ProcessCountsApplyConfiguration {
	b.LogRouter = &value
	return b
}

// WithFastRestore sets the FastRestore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FastRestore field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithFastRestore(value int) *ProcessCountsApplyConfiguration {
	b.FastRestore = &value
	return b
}

// WithDataDistributor sets the DataDistributor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataDistributor field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithDataDistributor(value int) *ProcessCountsApplyConfiguration {
	b.DataDistributor = &value
	return b
}

// WithCoordinator sets the Coordinator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Coordinator field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithCoordinator(value int) *ProcessCountsApplyConfiguration {
	b.Coordinator = &value
	return b
}

// WithRatekeeper sets the Ratekeeper field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ratekeeper field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithRatekeeper(value int) *ProcessCountsApplyConfiguration {
	b.Ratekeeper = &value
	return b
}

// WithStorageCache sets the StorageCache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageCache field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithStorageCache(value int) *ProcessCountsApplyConfiguration {
	b.StorageCache = &value
	return b
}

// WithBackupWorker sets the BackupWorker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupWorker field is set to the value of the last call.
func (b *ProcessCountsApplyConfiguration) WithBackupWorker(value int) *ProcessCountsApplyConfiguration {
	b.BackupWorker = &value
	return b
}
