// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ProcessGroupStatusApplyConfiguration represents a declarative configuration of the ProcessGroupStatus type for use
// with apply.
//
// ProcessGroupStatus represents the status of a ProcessGroup.
type ProcessGroupStatusApplyConfiguration struct {
	// ProcessGroupID represents the ID of the process group
	ProcessGroupID *apiv1beta2.ProcessGroupID `json:"processGroupID,omitempty"`
	// ProcessClass represents the class the process group has.
	ProcessClass *apiv1beta2.ProcessClass `json:"processClass,omitempty"`
	// Addresses represents the list of addresses the process group has been known to have.
	Addresses []string `json:"addresses,omitempty"`
	// RemoveTimestamp if not empty defines when the process group was marked for removal.
	RemovalTimestamp *v1.Time `json:"removalTimestamp,omitempty"`
	// ExclusionTimestamp defines when the process group has been fully excluded.
	// This is only used within the reconciliation process, and should not be considered authoritative.
	ExclusionTimestamp *v1.Time `json:"exclusionTimestamp,omitempty"`
	// ExclusionSkipped determines if exclusion has been skipped for a process, which will allow the process group to be removed without exclusion.
	ExclusionSkipped *bool `json:"exclusionSkipped,omitempty"`
	// ProcessGroupConditions represents a list of degraded conditions that the process group is in.
	ProcessGroupConditions []*apiv1beta2.ProcessGroupCondition `json:"processGroupConditions,omitempty"`
	// FaultDomain represents the last seen fault domain from the cluster status. This can be used if a Pod or process
	// is not running and would be missing in the cluster status.
	FaultDomain *apiv1beta2.FaultDomain `json:"faultDomain,omitempty"`
}

// ProcessGroupStatusApplyConfiguration constructs a declarative configuration of the ProcessGroupStatus type for use with
// apply.
func ProcessGroupStatus() *ProcessGroupStatusApplyConfiguration {
	return &ProcessGroupStatusApplyConfiguration{}
}

// WithProcessGroupID sets the ProcessGroupID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessGroupID field is set to the value of the last call.
func (b *ProcessGroupStatusApplyConfiguration) WithProcessGroupID(value apiv1beta2.ProcessGroupID) *ProcessGroupStatusApplyConfiguration {
	b.ProcessGroupID = &value
	return b
}

// WithProcessClass sets the ProcessClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessClass field is set to the value of the last call.
func (b *ProcessGroupStatusApplyConfiguration) WithProcessClass(value apiv1beta2.ProcessClass) *ProcessGroupStatusApplyConfiguration {
	b.ProcessClass = &value
	return b
}

// WithAddresses adds the given value to the Addresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Addresses field.
func (b *ProcessGroupStatusApplyConfiguration) WithAddresses(values ...string) *ProcessGroupStatusApplyConfiguration {
	for i := range values {
		b.Addresses = append(b.Addresses, values[i])
	}
	return b
}

// WithRemovalTimestamp sets the RemovalTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemovalTimestamp field is set to the value of the last call.
func (b *ProcessGroupStatusApplyConfiguration) WithRemovalTimestamp(value v1.Time) *ProcessGroupStatusApplyConfiguration {
	b.RemovalTimestamp = &value
	return b
}

// WithExclusionTimestamp sets the ExclusionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExclusionTimestamp field is set to the value of the last call.
func (b *ProcessGroupStatusApplyConfiguration) WithExclusionTimestamp(value v1.Time) *ProcessGroupStatusApplyConfiguration {
	b.ExclusionTimestamp = &value
	return b
}

// WithExclusionSkipped sets the ExclusionSkipped field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExclusionSkipped field is set to the value of the last call.
func (b *ProcessGroupStatusApplyConfiguration) WithExclusionSkipped(value bool) *ProcessGroupStatusApplyConfiguration {
	b.ExclusionSkipped = &value
	return b
}

// WithProcessGroupConditions adds the given value to the ProcessGroupConditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessGroupConditions field.
func (b *ProcessGroupStatusApplyConfiguration) WithProcessGroupConditions(values ...**apiv1beta2.ProcessGroupCondition) *ProcessGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProcessGroupConditions")
		}
		b.ProcessGroupConditions = append(b.ProcessGroupConditions, *values[i])
	}
	return b
}

// WithFaultDomain sets the FaultDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FaultDomain field is set to the value of the last call.
func (b *ProcessGroupStatusApplyConfiguration) WithFaultDomain(value apiv1beta2.FaultDomain) *ProcessGroupStatusApplyConfiguration {
	b.FaultDomain = &value
	return b
}
