// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
	v1 "k8s.io/api/core/v1"
)

// ProcessSettingsApplyConfiguration represents a declarative configuration of the ProcessSettings type for use
// with apply.
//
// ProcessSettings defines process-level settings.
type ProcessSettingsApplyConfiguration struct {
	// PodTemplate allows customizing the pod. If a container image with a tag is specified the operator
	// will throw an error and stop processing the cluster.
	PodTemplate *v1.PodTemplateSpec `json:"podTemplate,omitempty"`
	// VolumeClaimTemplate allows customizing the persistent volume claim for the
	// pod.  This will be ignored by the operator for stateless processes.
	VolumeClaimTemplate *v1.PersistentVolumeClaim `json:"volumeClaimTemplate,omitempty"`
	// CustomParameters defines additional parameters to pass to the fdbserver
	// process. Only parameters for the [fdbserver] section are supported. Parameters
	// from the [general] and [fdbmonitor] section are not supported. For more Information
	// see: https://apple.github.io/foundationdb/configuration.html#general-section
	CustomParameters *apiv1beta2.FoundationDBCustomParameters `json:"customParameters,omitempty"`
}

// ProcessSettingsApplyConfiguration constructs a declarative configuration of the ProcessSettings type for use with
// apply.
func ProcessSettings() *ProcessSettingsApplyConfiguration {
	return &ProcessSettingsApplyConfiguration{}
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *ProcessSettingsApplyConfiguration) WithPodTemplate(value v1.PodTemplateSpec) *ProcessSettingsApplyConfiguration {
	b.PodTemplate = &value
	return b
}

// WithVolumeClaimTemplate sets the VolumeClaimTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeClaimTemplate field is set to the value of the last call.
func (b *ProcessSettingsApplyConfiguration) WithVolumeClaimTemplate(value v1.PersistentVolumeClaim) *ProcessSettingsApplyConfiguration {
	b.VolumeClaimTemplate = &value
	return b
}

// WithCustomParameters sets the CustomParameters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomParameters field is set to the value of the last call.
func (b *ProcessSettingsApplyConfiguration) WithCustomParameters(value apiv1beta2.FoundationDBCustomParameters) *ProcessSettingsApplyConfiguration {
	b.CustomParameters = &value
	return b
}
