// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// ProcessGroupConditionApplyConfiguration represents a declarative configuration of the ProcessGroupCondition type for use
// with apply.
//
// ProcessGroupCondition represents a degraded condition that a process group is in.
type ProcessGroupConditionApplyConfiguration struct {
	// Name of the condition
	ProcessGroupConditionType *apiv1beta2.ProcessGroupConditionType `json:"type,omitempty"`
	// Timestamp when the Condition was observed
	Timestamp *int64 `json:"timestamp,omitempty"`
}

// ProcessGroupConditionApplyConfiguration constructs a declarative configuration of the ProcessGroupCondition type for use with
// apply.
func ProcessGroupCondition() *ProcessGroupConditionApplyConfiguration {
	return &ProcessGroupConditionApplyConfiguration{}
}

// WithProcessGroupConditionType sets the ProcessGroupConditionType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessGroupConditionType field is set to the value of the last call.
func (b *ProcessGroupConditionApplyConfiguration) WithProcessGroupConditionType(value apiv1beta2.ProcessGroupConditionType) *ProcessGroupConditionApplyConfiguration {
	b.ProcessGroupConditionType = &value
	return b
}

// WithTimestamp sets the Timestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timestamp field is set to the value of the last call.
func (b *ProcessGroupConditionApplyConfiguration) WithTimestamp(value int64) *ProcessGroupConditionApplyConfiguration {
	b.Timestamp = &value
	return b
}
