// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// RequiredAddressSetApplyConfiguration represents a declarative configuration of the RequiredAddressSet type for use
// with apply.
//
// RequiredAddressSet provides settings for which addresses we need to listen
// on.
type RequiredAddressSetApplyConfiguration struct {
	// TLS defines whether we need to listen on a TLS address.
	TLS *bool `json:"tls,omitempty"`
	// NonTLS defines whether we need to listen on a non-TLS address.
	NonTLS *bool `json:"nonTLS,omitempty"`
}

// RequiredAddressSetApplyConfiguration constructs a declarative configuration of the RequiredAddressSet type for use with
// apply.
func RequiredAddressSet() *RequiredAddressSetApplyConfiguration {
	return &RequiredAddressSetApplyConfiguration{}
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *RequiredAddressSetApplyConfiguration) WithTLS(value bool) *RequiredAddressSetApplyConfiguration {
	b.TLS = &value
	return b
}

// WithNonTLS sets the NonTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NonTLS field is set to the value of the last call.
func (b *RequiredAddressSetApplyConfiguration) WithNonTLS(value bool) *RequiredAddressSetApplyConfiguration {
	b.NonTLS = &value
	return b
}
