// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// RoleCountsApplyConfiguration represents a declarative configuration of the RoleCounts type for use
// with apply.
//
// RoleCounts represents the roles whose counts can be customized.
type RoleCountsApplyConfiguration struct {
	Storage       *int `json:"storage,omitempty"`
	Logs          *int `json:"logs,omitempty"`
	Proxies       *int `json:"proxies,omitempty"`
	CommitProxies *int `json:"commit_proxies,omitempty"`
	GrvProxies    *int `json:"grv_proxies,omitempty"`
	Resolvers     *int `json:"resolvers,omitempty"`
	LogRouters    *int `json:"log_routers,omitempty"`
	RemoteLogs    *int `json:"remote_logs,omitempty"`
}

// RoleCountsApplyConfiguration constructs a declarative configuration of the RoleCounts type for use with
// apply.
func RoleCounts() *RoleCountsApplyConfiguration {
	return &RoleCountsApplyConfiguration{}
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithStorage(value int) *RoleCountsApplyConfiguration {
	b.Storage = &value
	return b
}

// WithLogs sets the Logs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logs field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithLogs(value int) *RoleCountsApplyConfiguration {
	b.Logs = &value
	return b
}

// WithProxies sets the Proxies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Proxies field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithProxies(value int) *RoleCountsApplyConfiguration {
	b.Proxies = &value
	return b
}

// WithCommitProxies sets the CommitProxies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitProxies field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithCommitProxies(value int) *RoleCountsApplyConfiguration {
	b.CommitProxies = &value
	return b
}

// WithGrvProxies sets the GrvProxies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrvProxies field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithGrvProxies(value int) *RoleCountsApplyConfiguration {
	b.GrvProxies = &value
	return b
}

// WithResolvers sets the Resolvers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resolvers field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithResolvers(value int) *RoleCountsApplyConfiguration {
	b.Resolvers = &value
	return b
}

// WithLogRouters sets the LogRouters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogRouters field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithLogRouters(value int) *RoleCountsApplyConfiguration {
	b.LogRouters = &value
	return b
}

// WithRemoteLogs sets the RemoteLogs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteLogs field is set to the value of the last call.
func (b *RoleCountsApplyConfiguration) WithRemoteLogs(value int) *RoleCountsApplyConfiguration {
	b.RemoteLogs = &value
	return b
}
