// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/FoundationDB/fdb-kubernetes-operator/v2/api/v1beta2"
)

// RoutingConfigApplyConfiguration represents a declarative configuration of the RoutingConfig type for use
// with apply.
//
// RoutingConfig allows configuring routing to our pods, and services that sit
// in front of them.
type RoutingConfigApplyConfiguration struct {
	// Headless determines whether we want to run a headless service for the
	// cluster.
	HeadlessService *bool `json:"headlessService,omitempty"`
	// PublicIPSource specifies what source a process should use to get its
	// public IPs.
	//
	// This supports the values `pod` and `service`.
	PublicIPSource *apiv1beta2.PublicIPSource `json:"publicIPSource,omitempty"`
	// PodIPFamily tells the pod which family of IP addresses to use.
	// You can use 4 to represent IPv4, and 6 to represent IPv6.
	// This feature requires dual-stack support in your Kubernetes environment.
	PodIPFamily *int `json:"podIPFamily,omitempty"`
	// UseDNSInClusterFile determines whether to use DNS names rather than IP
	// addresses to identify coordinators in the cluster file. This requires
	// FoundationDB 7.0+.
	UseDNSInClusterFile *bool `json:"useDNSInClusterFile,omitempty"`
	// DefineDNSLocalityFields determines whether to define pod DNS names on pod
	// specs and provide them in the locality arguments to fdbserver.
	//
	// This is ignored if UseDNSInCluster is true.
	DefineDNSLocalityFields *bool `json:"defineDNSLocalityFields,omitempty"`
	// DNSDomain defines the cluster domain used in a DNS name generated for a
	// service.
	// The default is `cluster.local`.
	DNSDomain *string `json:"dnsDomain,omitempty"`
}

// RoutingConfigApplyConfiguration constructs a declarative configuration of the RoutingConfig type for use with
// apply.
func RoutingConfig() *RoutingConfigApplyConfiguration {
	return &RoutingConfigApplyConfiguration{}
}

// WithHeadlessService sets the HeadlessService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeadlessService field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithHeadlessService(value bool) *RoutingConfigApplyConfiguration {
	b.HeadlessService = &value
	return b
}

// WithPublicIPSource sets the PublicIPSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicIPSource field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithPublicIPSource(value apiv1beta2.PublicIPSource) *RoutingConfigApplyConfiguration {
	b.PublicIPSource = &value
	return b
}

// WithPodIPFamily sets the PodIPFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodIPFamily field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithPodIPFamily(value int) *RoutingConfigApplyConfiguration {
	b.PodIPFamily = &value
	return b
}

// WithUseDNSInClusterFile sets the UseDNSInClusterFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseDNSInClusterFile field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithUseDNSInClusterFile(value bool) *RoutingConfigApplyConfiguration {
	b.UseDNSInClusterFile = &value
	return b
}

// WithDefineDNSLocalityFields sets the DefineDNSLocalityFields field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefineDNSLocalityFields field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithDefineDNSLocalityFields(value bool) *RoutingConfigApplyConfiguration {
	b.DefineDNSLocalityFields = &value
	return b
}

// WithDNSDomain sets the DNSDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSDomain field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithDNSDomain(value string) *RoutingConfigApplyConfiguration {
	b.DNSDomain = &value
	return b
}
