// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// TaintReplacementOptionApplyConfiguration represents a declarative configuration of the TaintReplacementOption type for use
// with apply.
//
// TaintReplacementOption defines the taint key and taint duration the operator will react to a tainted node
// Example of TaintReplacementOption
// - key: "example.org/maintenance"
// durationInSeconds: 7200 # Ensure the taint is present for at least 2 hours before replacing Pods on a node with this taint.
// - key: "*" # The wildcard would allow to define a catch all configuration
// durationInSeconds: 3600 # Ensure the taint is present for at least 1 hour before replacing Pods on a node with this taint
//
// Setting durationInSeconds to the maximum of int64 will practically disable the taint key.
// When a Node taint key matches both an exact TaintReplacementOption key and a wildcard key, the exact matched key will be used.
type TaintReplacementOptionApplyConfiguration struct {
	// Tainted key
	Key *string `json:"key,omitempty"`
	// The tainted key must be present for DurationInSeconds before operator replaces pods on the node with this taint;
	// DurationInSeconds cannot be a negative number.
	DurationInSeconds *int64 `json:"durationInSeconds,omitempty"`
}

// TaintReplacementOptionApplyConfiguration constructs a declarative configuration of the TaintReplacementOption type for use with
// apply.
func TaintReplacementOption() *TaintReplacementOptionApplyConfiguration {
	return &TaintReplacementOptionApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *TaintReplacementOptionApplyConfiguration) WithKey(value string) *TaintReplacementOptionApplyConfiguration {
	b.Key = &value
	return b
}

// WithDurationInSeconds sets the DurationInSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DurationInSeconds field is set to the value of the last call.
func (b *TaintReplacementOptionApplyConfiguration) WithDurationInSeconds(value int64) *TaintReplacementOptionApplyConfiguration {
	b.DurationInSeconds = &value
	return b
}
