// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// VersionFlagsApplyConfiguration represents a declarative configuration of the VersionFlags type for use
// with apply.
//
// VersionFlags defines internal flags for new features in the database.
type VersionFlagsApplyConfiguration struct {
	LogSpill   *int `json:"log_spill,omitempty"`
	LogVersion *int `json:"log_version,omitempty"`
}

// VersionFlagsApplyConfiguration constructs a declarative configuration of the VersionFlags type for use with
// apply.
func VersionFlags() *VersionFlagsApplyConfiguration {
	return &VersionFlagsApplyConfiguration{}
}

// WithLogSpill sets the LogSpill field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogSpill field is set to the value of the last call.
func (b *VersionFlagsApplyConfiguration) WithLogSpill(value int) *VersionFlagsApplyConfiguration {
	b.LogSpill = &value
	return b
}

// WithLogVersion sets the LogVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogVersion field is set to the value of the last call.
func (b *VersionFlagsApplyConfiguration) WithLogVersion(value int) *VersionFlagsApplyConfiguration {
	b.LogVersion = &value
	return b
}
