name: Bug Report
description: Report a bug encountered while operating the FDB Kubernetes operator
labels: bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
        For security related issues please contact privately fdb-oss-security@group.apple.com.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: textarea
    id: fdbOperatorVersion
    attributes:
      label: FDB Kubernetes operator
      value: |
        <details>

        ```console
        $ kubectl fdb version
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: kubeVersion
    attributes:
      label: Kubernetes version
      value: |
        <details>

        ```console
        $ kubectl version
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: cloudProvider
    attributes:
      label: Cloud provider
      value: |
        <details>

        </details>
    validations:
      required: true
