apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: FDB_BLOB_CREDENTIALS
          value: "/tmp/fdb-backup-credentials/credentials"
        volumeMounts:
        - mountPath: /tmp/fdb-backup-credentials
          name: fdb-backup-credentials
          readOnly: true
      volumes:
      - name: fdb-backup-credentials
        secret:
          secretName: backup-credentials
