apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          image: fdb-kubernetes-operator:latest
          imagePullPolicy: IfNotPresent
