apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- test_certs.yaml
- backup_credentials.yaml
- debug_logs.yaml

resources:
- ../deployment
- ../minio

images:
- name: foundationdb/fdb-kubernetes-operator
  newName: fdb-kubernetes-operator
  newTag: latest
