apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: DISABLE_SIDECAR_TLS_CHECK
          value: "1"
        - name: FDB_TLS_CERTIFICATE_FILE
          value: /tmp/fdb-certs/tls.crt
        - name: FDB_TLS_CA_FILE
          value: /tmp/fdb-certs/tls.crt
        - name: FDB_TLS_KEY_FILE
          value: /tmp/fdb-certs/tls.key
        volumeMounts:
        - mountPath: /tmp/fdb-certs
          name: fdb-certs
          readOnly: true
      volumes:
      - name: fdb-certs
        secret:
          secretName: fdb-kubernetes-operator-secrets