# Those credentials are only intended for testing.
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
stringData:
  credentials: |
    {
        "accounts": {
            "seaweedfs@seaweedfs": {
                "secret" : "tot4llys3cure"
            },
            "seaweedfs@seaweedfs:8333": {
                "secret" : "tot4llys3cure"
            }
        }
    }
